### ISSUE TITLE
Column not found: 1054 Unknown column 'm0_.context' in 'where clause'

### ISSUE THREAD

**Issue by amzain83** [sonata-project/SonataMediaBundle#100]
Hi there 

i am trying to use SonataMediaBundle 
and my config.yml is like that

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

```
orm:
    auto_generate_proxy_classes: %kernel.debug%
    auto_mapping: true
    #entity_managers:
     #     default:
      #        mappings:
       #           ApplicationSonataMediaBundle: ~ 
```

"""
when i remove comments and comment auto_mapping: true the admin doesn't work and gives 

 Class Application\Sonata\UserBundle\Entity\User is not a valid entity or mapped super class. 

So any help ????!!!
