### ISSUE TITLE
The type hint of parameter "category" in method "setCategory"

### ISSUE THREAD

**Issue by jenyak** [sonata-project/SonataMediaBundle#1133]
#### Sonata packages

``` bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.x-dev 114ee15    The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.1.1              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2                Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.x-dev 41efe08    Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0              Lightweight Exporter library
sonata-project/intl-bundle               2.2.4              Symfony SonataIntlBundle
sonata-project/media-bundle              dev-master 62360e8 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0              Symfony SonataNotificationBundle
```
#### Symfony packages

``` bash
$ composer show symfony/*
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.12 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.12 The Symfony PHP framework
```
#### PHP version

``` bash
PHP 7.0.11-1 (cli) ( NTS )
```
## Subject

Got error when try to clear cache in production env. I think this bug related to PR #1086 
## Steps to reproduce

install sonata admin `3.x-dev` according [manual](https://sonata-project.org/bundles/admin/3-x/doc/getting_started/installation.html)
install sonata media `dev-master` according [manual](https://sonata-project.org/bundles/media/master/doc/reference/installation.html) 

**sonata_media config:**

```
sonata_media:
    force_disable_category: true
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
```

`$ app/console c:clear -e=prod`
## Expected results

clear cache, no errors
## Actual results

```
  [Doctrine\Common\Proxy\Exception\UnexpectedValueException]                                                                        
  The type hint of parameter "category" in method "setCategory" in class "Application\Sonata\MediaBundle\Entity\Media" is invalid.  

  [ReflectionException]                                                     
  Class Sonata\ClassificationBundle\Model\CategoryInterface does not exist  

```
