### ISSUE TITLE
Make "formats" optional

### ISSUE THREAD

**Issue by hpatoio** [sonata-project/SonataMediaBundle#1135]
Now you have to specify the "formats" for each media. Would be nice to have this section optional. For instance I want my media to be uploaded but left untouched by the system !  

Is think this is someone possible by create a custom provider but it would be nice to have the feature built in.

**Comment by btribouillet** [comment]
I think this is a good idea. I'm actually using imgix for one project so i don't need to format any images. I just need to upload the actual image to my cdn since imgix will do the rest.

**Comment by greg0ire** [comment]
We accept documented and tested contributions.

**Comment by btribouillet** [comment]
This is the required [config](https://sonata-project.org/bundles/media/master/doc/reference/advanced_configuration.html) for sonata media.    

    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image

            # Make the formats option optional (formats is required here, otherwise it will trigger an error
            formats:
                square_thumbnail:   { width: 200 , height: 200, quality: 90}


> The child node "formats" at path "sonata_media.contexts.default" must be configured.

**Comment by greg0ire** [comment]
So we should make it optional depending on the providers?

**Comment by btribouillet** [comment]
I have not use the other providers but i guess that the format apply to the image provider. I don't think that the formats configured below apply to file or youtube/dailymotion providers.

    providers:
        - sonata.media.provider.dailymotion
        - sonata.media.provider.youtube
        - sonata.media.provider.image
        - sonata.media.provider.file

    formats:
        small: { width: 150 , quality: 95}
        big:   { width: 500 , quality: 90}

At least for image provider if no formats are specified it should straight upload the image as it is to the targeted folder or cdn.

**Comment by greg0ire** [comment]
That makes little to no sense… I think there is something very wrong with the way options / formats are passed in this bundle, see [this comment](https://github.com/sonata-project/SonataMediaBundle/pull/1144#issuecomment-262778953) from @hug963

**Comment by btribouillet** [comment]
i agree, @hug963 got a point.

**Comment by hug963** [comment]
The whole point of the providers is to produce thumbnails etc.

You can leave `formats` empty and the only format generated will be the `admin` format which is needed for the backend.

```yaml
    contexts:
        default:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
```

and then use the `reference` format for the helpers:

```twig
    {% media media, 'reference' %}
```

or you can extend the file provider with the extensions you need and add some extensions and mime types:

```yaml
    sonata_media:
    providers:
        file:
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain']
```
