### ISSUE TITLE
Purpose of 'constraint'

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#1180]
I'm trying to figure out what the purpose of the `constraint` is. It was introduced 6!!! years ago: https://github.com/sonata-project/SonataMediaBundle/commit/f960e01c68c28cd9717f1032be5f06ab4e9144b7#diff-207faf90440ba86464531bf82b81c280R67

Definition: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/DependencyInjection/Configuration.php#L45

Passed as a format config: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Provider/BaseProvider.php#L118

AFAIK we define this property, but we never use it. Can we removed this or use if to define validator constraint to them?

**Comment by greg0ire** [comment]
Looks like it is supposed to be a boolean (saw that in the test). Maybe if means "constraint to given format".

**Comment by greg0ire** [comment]
Saw that in the log : `->resize($settings['width'], $settings['constraint'] ? $settings['constraint'] :  $settings['height'])`

**Comment by greg0ire** [comment]
Later changed to `->resize($settings['width'], $height, !$height ? \Imagine\GD\Command\Resize::INFER_HEIGHT : null)`

**Comment by greg0ire** [comment]
I'd be ok for removing the property. If people need it, we will know, revert and document.

**Comment by JonathanBaudoin** [comment]
I need it. I **use** it. Its' usefull to pass options for a custom resizer.

**Comment by greg0ire** [comment]
@JonathanBaudoin  Can you show us an example?

**Comment by JonathanBaudoin** [comment]
In my company we work with clients who send us a lot of photos. Then we display these photos on a few client website pages. For an example, on the homepage, all photos **must** be as 250 px squares, with crop if it's necessary. But on an other page, they **must** be 350 px width, with ratio keeping, adding blank if it's necessary. So we have twice behaviors for the same context:

```yml
sonata_media:
    contexts
        photos:
            formats:
                homepage:  { width: 250, quality: 100, constraint: 'type: square' }
                other_page: { width: 350, quality: 100, constraint: 'ratio: true, fill: #ffffff' }
```

This is an example (not prod code), and we have a lot of others cases. But that's the only way we find to give options to our custom resizer, as we can not add a resizer for a given format.

I don't know if I'm clear; if I'm not, tell me.
