### ISSUE TITLE
FormatThumbnail generate called multiple times if context have same base name

### ISSUE THREAD

**Issue by nicolasricci** [sonata-project/SonataMediaBundle#1202]
Hi,

Is there any particular reason behind the following condition in FomatThumbnail generate method?

```php
if (substr($format, 0, strlen($media->getContext())) == $media->getContext() || $format === 'admin') {
```

I have the following two contexts in my project with a custom resizer checking the minimum height and width of the media.

```yaml
sonata_media:
    contexts:
        brand:
            providers:
              - sonata.media.provider.image

            formats:
                small: { width: 128, height: 83, constraint: false, quality: 100}

        brand_banner:
            providers:
              - sonata.media.provider.image

            formats:
                small: { width: 974, height: 283, constraint: false, quality: 100}
    providers:
        image:
            resizer: sonata.media.resizer.fixedDimensions
```

The issue is because the above condition matches both contexts an exception is thrown when trying to upload the `brand` context image.

I have renamed my context differently in the meantime but was wondering the logic behind the `substr` instead of having a simple `$format == $media->getContext()`

Thanks in advance for your feedback on this.
