### ISSUE TITLE
Unable to create png thumbnails

### ISSUE THREAD

**Issue by pulse00** [sonata-project/SonataMediaBundle#121]
I'm unable to create a media format for images with the format `png`:

``` yml
      contexts:
        default:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 150 , quality: 100, format: png}

```

I've already desperately tried to replace every occurrence of `jpg` in the bundles sources with `png`. But still, every generated thumbnail for the above format `small` is a `jpg` instead of a `png`.
