### ISSUE TITLE
API: bug in ApiController or NelmioApiDocBundle, POST fields are ignored

### ISSUE THREAD

**Issue by lemorragia** [sonata-project/SonataMediaBundle#1244]
## Sonata Packages
```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.16.0          The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.1           Symfony SonataBlockBundle
sonata-project/cache                     1.x-dev 1dada19 Cache library
sonata-project/classification-bundle     3.2.1           Symfony SonataClassificationBundle
sonata-project/core-bundle               3.2.0           Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1           Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.x-dev 3a5b6cb Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3           Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10          Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.x-dev 069f517 Lightweight Exporter library
sonata-project/google-authenticator      1.x-dev 474c908 Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4           Symfony SonataIntlBundle
sonata-project/media-bundle              3.5.0           Symfony SonataMediaBundle
sonata-project/notification-bundle       3.x-dev 46cc9d3 Symfony SonataNotificationBundle
sonata-project/user-bundle               3.2.1           Symfony SonataUserBundle
```
## Subject
I'm using sonata media api, and i'm experiencing two strange behaviours which are probably linked:

- i think there's something wrong with either with Api/MediaController or NelmioApiDocBundle. Going to /api/doc (in my application using the standard,  untouched, sonata_api_media form, but the problem is still there in demo.sonata-project.com container demo) and trying to post a new media results in a validation failed error "This form should not contain extra fields.". If i allow_extra_fields in the form configuration (directly in the Sonata/Controller/Api/MediaController.php , just for testing purposes) the media is added, but all the fields set in the POST request are ignored (eg. enabled is always false, the name of the media is always replaced by the filename, etc.). If i force-print "$form->getExtraData()" inside the controller, turns out the ExtraData array contains:
`Array
(
    [_format] => json
    [provider] => sonata.media.provider.image
)`
If i try to cURL the same call, removing the "_format" parameter from the request, the media is added, but once again the fields i post are ignored. It seems strange: maybe NelmioApiDoc does something wrong here with the parameters, or maybe there's a problem in the MediaController handling of the parameters. 

- the second one is possibly the same issue: i'm trying to add additional fields to the Media entity in a way that i can use the additional fields through the APIs. The bundle is currently extended in Application\Sonata\MediaBundle generated by easy-extends bundle. The additional field are ignored, though they correctly appear in the /api/doc section. Probably they are ignored because _every other field is_ ;-)

## Steps to reproduce
Going to demo.sonata-project.com, in the /api/doc section, using 
"POST /api/media/providers/sonata.media.provider.image/media.json"
call should result in the same behaviour.

**Comment by pauleau** [comment]
Hi, Do you resolve this ?!
I'm trying for days to upload picture using Media Bundle API but I can't manage to send the structure wanted I think.. 
the $form in /API/MediaController is always empty, not filled by the request. 

How do you construct the request ? I'm using POSTMAN to test with multipart/form-data or Json and the fields specified in the sonata doc. 

Your help will be very very appreciate, I'm quite desesperate.

**Comment by lemorragia** [comment]
Hi @pauleau .

I'm still struggling with this, but i actually use a way around it for the moment which works.

If you look at the SonataMediaBundle/Controller/Api/MediaController.php you'll see the handleWriteMedium function.

I'm extending the controller and before the "createNamed" i manually remove the "_format" parameter from the request with

`$request->request->remove('_format');`

This is bad, dirty and feels very wrong. But it works until this problem is resolved(if it is a problem at all).

**Comment by pauleau** [comment]
Thank for your reply. 
Yes I'm watching/returning variables in this function to understand why what I send not fill up the form. 

About your format : how do you construct your request ? 
xxxx/api/providers/sonata.media.provider.image/media
using form-data ? json ? 
Which is the structure of your request ?

May ours problems can be solved mutualising our way to do.

**Comment by lemorragia** [comment]
Hi

i actually use only json format for the responses, for now:

```yaml
fos_rest:
       routing_loader:
           default_format: json
           include_format: false
```

I did not work on this code in the last few months, but i tested these apis a while ago, i'll paste here one test of the POST section

```php
$data = array(
            'name' => 'TestMedia',
            'description' => 'TestMediaDescription',
            'enabled' => 1,
            'binaryContent' => %PATH%,
            'providerStatus' => 1,
            'providerReference' => %FILENAME%,
            'context' => %CONTEXT%
);

$this->client->request('POST',%URL%, $data);
$this->assertStatusCode(200, $this->client);
$this->asserter()->assertJsonResponse($this->client->getResponse());
$this->asserter()->assertResponsePropertiesExist($this->client->getResponse(), array(
            'name',
            'description',
            'enabled',
            'provider_name',
            'provider_reference',
            'context',
            'id'
));
```
This should work as the test pass right now

**Comment by pauleau** [comment]
Ok thank you. 
I did the same using POSTMAN. Using json format or multipart/form-data as mentionned in the [documentation](https://sonata-project.org/bundles/media/3-x/doc/reference/api.html)

Json raw : 
`{
	"name": "namee",
	"description": "description",
	"copyright": "copyright",
	"authorName": "authorName",
	"cdnIsFlushable": true,
	"enabled": true,
	"binaryContent": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABaQAAASMCAYAAAB3UopLAAAMF2lDQ1BJQ0MgUHJvZmlsZQAASImVlwdUU0kXx+eVFEJCC0RASuhNkF6l9yIgHWyEJEAoIQSCih1ZVHAtqFiwoisgCq4FkLUiioVFsPcNKirKuliwofJNEkD",
	"filename": "testfieldname.jpg"
}`

But my form always return empty 
`{
    "children": {
        "name": {},
        "description": {},
        "enabled": {},
        "copyright": {},
        "authorName": {},
        "context": {},
        "cdnIsFlushable": {},
        "binaryContent": {},
        "contentType": {}
    }
}`

As its not filled or get data from the request. The request that I return to have a look, and which seems to be OK..

In my config : 

```
fos_rest:
    routing_loader:
        include_format: false
    # After API media try
    # view:
    #     view_response_listener: true
    param_fetcher_listener: true
    # Adding API media try
    body_listener:          true
    view:
        view_response_listener: force
    body_converter:
        enabled: true
        validate: true
    # End Adding API media try
    format_listener:
        rules:
            - { path: '^/admin', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
            - { path: '^/register', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
            - { path: '^/login', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
            # Adding API media try
            - { path: '^/api', priorities: ['json'], fallback_format: 'json', prefer_extension: false }
            - { path: '^/', priorities: ['json'], fallback_format: 'json', prefer_extension: false }
```

**Comment by pauleau** [comment]
In your json structure, do you think all of them are required ? 
What do you have under %PATH% and other vars ?

I just retest (after reconfirm to POSTMAN that my request should use POST method), I have now : 
```
{
    "code": 400,
    "message": "Validation Failed",
    "errors": {
        "errors": [
            "This value should not be null.",
            "This value should not be blank.",
            "This value should not be null.",
            "This value should not be blank.",
            "This form should not contain extra fields."
        ],
        "children": {
            "name": {
                "errors": [
                    "This value should not be null.",
                    "This value should not be blank."
                ]
            },
            "description": {},
            "enabled": {},
            "copyright": {},
            "authorName": {},
            "context": {},
            "cdnIsFlushable": {},
            "binaryContent": {},
            "contentType": {}
        }
    }
}
```

**Comment by lemorragia** [comment]
Strange that gives you an error on the "name" field. That i know of, only "name","context" and "binaryContent" are required, and the rest is optional(i'm quite sure about this, i have a python script that uses these apis and sends only these 3 fields).

Maybe this goes beyond my understanding: i don't use format_listener->rules in my configuration. Here's my full fos_rest configuration:

```yaml
fos_rest:
    versioning: #I'm using versioning, for this project but is an optional feature
        enabled: true
        default_version: 2.0 

    param_fetcher_listener: true
    body_listener:          true
    format_listener:        true
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: force
    body_converter:
        enabled: false
        validate: true
    exception:
        messages:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true

```

so: name is any string("test" should work), context is a string representing one of the configured sonata context ("default" should work, is the default context which is not removable), for binaryContent i use, in my tests, an absolute system path (/home/user/webapp/..../xyxxz.png'), in my python scripts i use the "files" parameter of the requests library, which is a multipart-encoded file in the request.

```python

filename = os.path.basename(fileToUploadPath)
files = { 'binaryContent': (filename, open(fileToUploadPath,'r+b'))}

payload = {'name': name, 'context': context}

requests.post(url, data=payload, files=files)

```
