### ISSUE TITLE
AddProviderCompilerPass parameter replacement

### ISSUE THREAD

**Issue by lightglitch** [sonata-project/SonataMediaBundle#1271]
After the change made by #1218 we no longer have the parameter replacement working in the providers configuration.

For example I use different filesystem for dev/staging/prod and to defined that I used a parameter:

```yaml
providers:
        file:
            filesystem: %sonata_media.filesystem%
```

Now I get an error saying that the service is %sonata_media.filesystem% doesn't exist.

**Comment by OskarStark** [comment]
@jlamur can you help here?

**Comment by jlamur** [comment]
@jordisala1991

**Comment by OskarStark** [comment]
Argh sorry, I was to fast, ofc I meant jordi... 😄

**Comment by jordisala1991** [comment]
It is strange if it does not work. It should... Are you still experiencing this behavior?

**Comment by benjaminrau** [comment]
@jordisala1991 I am experiencing the same issue right now - going back to 3.4 i can use parameters for service definition. 

On 3.5 i get the following error:
````
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "sonata.media.provider.image" has a dependenc  
  y on a non-existent service "%media_filesystem%"
```

parameters.yml
```
media_filesystem: sonata.media.filesystem.local
```

config.yml
```
 providers:
        file:
            filesystem: '%media_filesystem%'
        image:
            filesystem: '%media_filesystem%'
```

It works fine on 3.5 if i change config.yml to:
```
 providers:
        file:
            filesystem: sonata.media.filesystem.local
        image:
            filesystem: sonata.media.filesystem.local
```
