### ISSUE TITLE
FatalThrowableError:  _construct() must be an instance of CategoryManagerInterface

### ISSUE THREAD

**Issue by ArmandArthur** [sonata-project/SonataMediaBundle#1279]
Hello,

Sorry but i have an error 👎 

```
(1/1) FatalThrowableError
Type error: Argument 1 passed to Sonata\MediaBundle\Model\CategoryManager::__construct() must be an instance of Sonata\ClassificationBundle\Model\CategoryManagerInterface, null given, called in C:\wamp64\www\master\var\cache\dev\appDevDebugProjectContainer.php on line 5991
```
This is my configuration doctrine_phpcr : 

```
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend:
            type: jackrabbit
            url:  http://localhost:8085/serveur/            
            # optional parameters for Jackalope
            parameters:
                jackalope.factory:                Jackalope\Factory
                jackalope.check_login_on_server:  false
                jackalope.disable_stream_wrapper: false
                jackalope.auto_lastmodified:      true
                # see below for how to configure the backend of your choice
        workspace: default
        username:  admin
        password:  admin
    # enable the ODM layer
    odm:
        mappings:
              SonataMediaBundle:
                  prefix: AppBundle\Application\Sonata\MediaBundle\PHPCR        
        #auto_mapping: true
        auto_generate_proxy_classes: '%kernel.debug%'
        locales:
            en: [de, fr]
            de: [en, fr]
            fr: [en, de]
``
My bundles : 
```
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\PHPCRBundle\DoctrinePHPCRBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
            //new Symfony\Bundle\AsseticBundle\AsseticBundle(),   
            new Sonata\CoreBundle\SonataCoreBundle(),
            new Sonata\BlockBundle\SonataBlockBundle(),
            new Knp\Bundle\MenuBundle\KnpMenuBundle(),
            new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),
            new Sonata\AdminBundle\SonataAdminBundle(),
            new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
            new Pix\SortableBehaviorBundle\PixSortableBehaviorBundle(),
            new Sonata\EasyExtendsBundle\SonataEasyExtendsBundle(),
            new FOS\UserBundle\FOSUserBundle(),
            new Sonata\UserBundle\SonataUserBundle('FOSUserBundle'),
            new AppBundle\Application\Sonata\UserBundle\ApplicationSonataUserBundle(),
            new Sonata\TranslationBundle\SonataTranslationBundle(),
            new Lexik\Bundle\TranslationBundle\LexikTranslationBundle(),
            new Ibrows\SonataTranslationBundle\IbrowsSonataTranslationBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),
            //new Sonata\DoctrineMongoDBAdminBundle\SonataDoctrineMongoDBAdminBundle(),
            new Sonata\MediaBundle\SonataMediaBundle(),
            new JMS\SerializerBundle\JMSSerializerBundle(),
            new AppBundle\Application\Sonata\MediaBundle\ApplicationSonataMediaBundle()

Could you help me please?
```

**Comment by ArmandArthur** [comment]
```
sonata_media:
    # if you don't use default namespace configuration
    class:
        media:        AppBundle\Application\Sonata\MediaBundle\Entity\Media
        gallery:      AppBundle\Application\Sonata\MediaBundle\Entity\Gallery
        #gallery_item: MyVendor\MediaBundle\Entity\GalleryItem
    
    # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    db_driver: doctrine_orm
    # you need to set a context
    default_context: default 
    contexts:
        # the default context is mandatory
        default:  
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
      
    providers:
        image:
            resizer: sonata.media.resizer.square    
```
