### ISSUE TITLE
Class Application\Sonata\ClassificationBundle\Entity\Context does not exist

### ISSUE THREAD

**Issue by ArmandArthur** [sonata-project/SonataMediaBundle#1280]
Hello,

I have this error... (sorry)

I changed namespaces into the folder MediaBundle and ClassificationBundle because they are in the folder
src/AppBundle.

I have the class Context in my entities.
The path should be is AppBundle\Application\Sonata\ClassificationBundle\Entity\Context

Or is : ==>

```
Class Application\Sonata\ClassificationBundle\Entity\Context does not exist

ReflectionException
in vendor\doctrine\common\lib\Doctrine\Common\Persistence\AbstractManagerRegistry.php (line 197)
        if (strpos($class, ':') !== false) {            list($namespaceAlias, $simpleClassName) = explode(':', $class, 2);            $class = $this->getAliasNamespace($namespaceAlias) . '\\' . $simpleClassName;        }        $proxyClass = new \ReflectionClass($class);        if ($proxyClass->implementsInterface($this->proxyInterfaceName)) {            if (! $parentClass = $proxyClass->getParentClass()) {                return null;            }
ReflectionClass->__construct('Application\\Sonata\\ClassificationBundle\\Entity\\Context')
in vendor\doctrine\common\lib\Doctrine\Common\Persistence\AbstractManagerRegistry.php (line 197)
AbstractManagerRegistry->getManagerForClass('Application\\Sonata\\ClassificationBundle\\Entity\\Context')
in vendor\sonata-project\core-bundle\Model\BaseManager.php (line 48)
BaseManager->getObjectManager()
in vendor\sonata-project\core-bundle\Model\BaseManager.php (line 154)
BaseManager->getRepository()
in vendor\sonata-project\core-bundle\Model\BaseManager.php (line 100)
BaseManager->find('default')
in vendor\sonata-project\classification-bundle\Entity\CategoryManager.php (line 344)
CategoryManager->getContext('default')
in vendor\sonata-project\classification-bundle\Entity\CategoryManager.php (line 136)
CategoryManager->getRootCategory('default')
in vendor\sonata-project\media-bundle\Model\CategoryManager.php (line 40)
CategoryManager->getRootCategory('default')
in vendor\sonata-project\media-bundle\Admin\BaseMediaAdmin.php (line 91)
BaseMediaAdmin->getPersistentParameters()
in vendor\sonata-project\admin-bundle\Admin\AbstractAdmin.php (line 2017)
AbstractAdmin->getPersistentParameter('hide_context')
in vendor\sonata-project\media-bundle\Admin\ORM\MediaAdmin.php (line 42)
MediaAdmin->configureDatagridFilters(object(DatagridMapper))
in vendor\sonata-project\admin-bundle\Admin\AbstractAdmin.php (line 838)
AbstractAdmin->buildDatagrid()
in vendor\sonata-project\admin-bundle\Admin\AbstractAdmin.php (line 1385)
AbstractAdmin->getDatagrid()
in vendor\sonata-project\media-bundle\Controller\MediaAdminController.php (line 64)
MediaAdminController->listAction(object(Request))
call_user_func_array(array(object(MediaAdminController), 'listAction'), array(object(Request)))
in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php (line 153)
HttpKernel->handleRaw(object(Request), 1)
in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php (line 68)
HttpKernel->handle(object(Request), 1, true)
in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php (line 171)
Kernel->handle(object(Request))
in web\app_dev.php (line 29)
```

**Comment by ArmandArthur** [comment]
I resolved my problem in adding : 

```
sonata_classification:
    class:
        tag:          AppBundle\Application\Sonata\ClassificationBundle\Entity\Tag
        category:     AppBundle\Application\Sonata\ClassificationBundle\Entity\Category
        collection:   AppBundle\Application\Sonata\ClassificationBundle\Entity\Collection
        media:        AppBundle\Application\Sonata\MediaBundle\Entity\Media
        context:      AppBundle\Application\Sonata\ClassificationBundle\Entity\Context

    admin:
        tag:
            class:        Sonata\ClassificationBundle\Admin\TagAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        category:
            class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
            controller:   SonataClassificationBundle:CategoryAdmin
            translation:  SonataClassificationBundle
        collection:
            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        context:
            class:        Sonata\ClassificationBundle\Admin\ContextAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle  
```

And enabled in my configuration

```
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    LexikTranslationBundle: ~
                    AppBundle:
                         type: ~
                         dir: "Entity"
                         prefix: AppBundle\Entity
                         is_bundle: ~
                    #SonataDoctrineMongoDBAdminBundle: ~
                    SonataClassificationBundle: ~
                    ApplicationSonataClassificationBundle: ~
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
```
