### ISSUE TITLE
No documentation for sonata media gallery form type in admin

### ISSUE THREAD

**Issue by multifinger** [sonata-project/SonataMediaBundle#1361]
using latest stable sonata versions of admin+media bundles+doctrine-orm

I've got an entity with gallery field, where gallery is sonata-media-gallery enitty
I want to create sonata admin form for that entity

Documentation of sonata https://sonata-project.org/bundles/admin/3-x/doc/reference/form_types.html have only media form type described. But gallery case is also important.

I've tried to create collection form type of media_types embedded (tried every existing form types of collection, various configuration with no luck)

PLease, add documentation with code example of how to create form type for gallery field

**Comment by multifinger** [comment]
Entity doctrine config:
```
AppBundle\Entity\Story:
    type: entity
...
    oneToOne:
        Gallery:
            targetEntity: Application\Sonata\MediaBundle\Entity\Gallery
            joinColumn:
                name: gallery_id
                referencedColumnName: id
                onDelete: "SET NULL"
```
