### ISSUE TITLE
Changed default srcset behaviour

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#1386]
## Subject

The `media` twig tag is broken.

## Steps to reproduce
Define some image formats in the configuration.

Create a template with the following code:
```twig
{% media post.image, 'general' %}
```

## Expected results

A simple image is displayed

```html
<img 
src="/uploads/media/news/0001/01/thumb_235_news_general.jpeg" width="1080" height="200">
```

## Actual results

An image with all available formats (include the raw reference format!) is create
```html
<img src="/uploads/media/news/0001/01/thumb_235_news_general.jpeg" 
srcset="/uploads/media/news/0001/01/thumb_235_news_general.jpeg 1080w, /uploads/media/news/0001/01/thumb_235_news_recent.jpeg 260w, /uploads/media/news/0001/01/91f2c4a0f87a8ef98d14de5d7448a05813e823be.jpeg 1280w" 
sizes="(max-width: 1080px) 100vw, 1080px" 
width="1080" height="200">
```

**Comment by hug963** [comment]
This is a feature of the media helper.

It is described in the docs: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/docs/reference/helpers.rst

Why do you think it is an issue?

**Comment by cussack** [comment]
Try `{% media post.image, 'general' with {'srcset': []} %}`

**Comment by cussack** [comment]
@core23 I found this to be an issue as well now. While it is probably a good thing to render responsive images by default, the reference image should not be included in the srcset. There is no programmatic control over its size and dimensions, so it should not be part of the documented „sensible defaults“.

What do you think? I need to remove it for a project anyway and can contribute the solution here.

**Comment by core23** [comment]
There are some pros and cons for the current solution.

In my projects I use the different image dimensions for different pages. So I have a list page where I don't want to render a big size image in any way and a detail page which has a different purpose.

The best way would be a config key with srcset groups:
```yaml
        default:
            group:
                list: [ 'small', 'icon' ]
                detail: [ 'big', 'reference' ]
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70, resizer: sonata.media.resizer.square}
                # You can pass through any custom option to resizer by using the resizer_options key
                icon:  { width: 32, quality: 70, resizer: your.custom.resizer, resizer_options: { custom_crop: true } }

```

```twig
{% media post.image, 'list' %}
```
