### ISSUE TITLE
Impossible to invoke a method ("id") on a null variable.

### ISSUE THREAD

**Issue by javichuteck** [sonata-project/SonataMediaBundle#1408]
### Environment
Symfony 3.4.4 + FOSBundleUser + Sonata Admin + Media Bundle

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.23.0 3.23.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.4.0  3.4.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  1.0.7  Cache library
sonata-project/core-bundle               3.5.1  3.5.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.7  3.1.7  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  1.7.1  Lightweight Exporter library
sonata-project/media-bundle              3.7.0  3.7.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.2.0  3.2.0  Symfony SonataNotificationBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.1.2 v3.1.2 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.4 v4.0.5 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.7.0 v1.7.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.7.0 v1.7.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.7.0 v1.7.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.7.0 v1.7.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1 v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 v3.0.3 Symfony SwiftmailerBundle
symfony/symfony            v3.4.4 v3.4.5 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 5.6.32 (cli) (built: Dec 29 2017 12:08:34) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

## Subject

I have installed Media Bundle.
I have configured it following the steps indicated in the Official documentation.

I have created a field in my entity Products to attach a catalog in PDF format.

I have added in Sonata Adminel field mapping.

When viewing the list of products in Sonata Admin, there is no problem, but when enter to edit or create a new product, give this error:

> Impossible to invoke a method ("id") on a null variable.

## Expected results
Should see the Product add/update form, and a field to upload the PDF, but it does not work.

## Actual results

> Impossible to invoke a method ("id") on a null variable.

This is the definition of my field to attach a PDF in my entity
```
/**
     * @var Media
     *
     * @ORM\ManyToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="fileCatalog_id", referencedColumnName="id")
     * })
     */
    private $fileCatalog;
```

This is the mapping of the field in the Sonata Admin form
```
->add('fileCatalog', 'sonata_type_model_list', array(
                        'required' => false,
                        'label'=>'Imagen Español'
                    ), array(
                            'link_parameters' => array(
                                'context' => 'default',
                                'provider' => 'sonata.media.provider.file',
                                'empty_on_new' => true,
                            )
                        )
                    )
```

Thanks

**Comment by greg0ire** [comment]
It looks as if there were no admin for `Application\Sonata\MediaBundle\Entity\Media`. Is there?

**Comment by javichuteck** [comment]
Actually, it's here:

<img width="384" alt="captura de pantalla 2018-03-04 a las 23 04 17" src="https://user-images.githubusercontent.com/13252388/36951153-7fef5fea-2000-11e8-9b72-e0862184241a.png">

**Comment by greg0ire** [comment]
The entity is there indeed, but I did not ask about the entity, I asked about the _admin_ .

**Comment by javichuteck** [comment]
I do not understand well what you tell me (I'm Spanish, and maybe I'm not understanding something right).

Could you give me some more detail to understand what is missing or what happens?

I followed all the steps of the documentation. I missed something to do?

**Comment by javichuteck** [comment]
The admin is here:

<img width="373" alt="captura de pantalla 2018-03-04 a las 23 12 22" src="https://user-images.githubusercontent.com/13252388/36951244-8ae355d6-2001-11e8-84f5-df3c228dcc69.png">

**Comment by greg0ire** [comment]
Well I'm french so maybe it's me that has difficulties getting things across?

Your screenshots shows many admins, but none of them is for Media. I believe that the admin for the media entity is in the media bundle, but for some reason, it can't be found.

**Comment by greg0ire** [comment]
I think you should share your configuration for the media bundle with us.

**Comment by javichuteck** [comment]
In my config.yml:

```
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            #directory:  "%kernel.root_dir%/../public/uploads/media" #flex
            directory:  "%kernel.root_dir%/../web/uploads/media" #non-flex
            create:     false

    providers:
        image:
            resizer: sonata.media.resizer.square #sonata.media.resizer.simple

    # if you don't use default namespace configuration
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia

```

**Comment by javichuteck** [comment]
in routing.yml

```
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
```
