### ISSUE TITLE
Problems linking media to an entity

### ISSUE THREAD

**Issue by abeljouve** [sonata-project/SonataMediaBundle#1410]
Hello,
I have a problem, i have a news doctrine entity and i want to attach an image to it and multiple files like PDF.
Firstly i am trying to attach the picture but i have an error when i save the entity:

`The form's view data is expected to be an instance of class Application\Sonata\MediaBundle\Entity\Media, but is a(n) string. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) string to an instance of Application\Sonata\MediaBundle\Entity\Media.`

Stack Trace:
```
Symfony\Component\Form\Exception\LogicException:
The form's view data is expected to be an instance of class Application\Sonata\MediaBundle\Entity\Media, but is a(n) string. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) string to an instance of Application\Sonata\MediaBundle\Entity\Media.

  at vendor\symfony\symfony\src\Symfony\Component\Form\Form.php:361
  at Symfony\Component\Form\Form->setData('ljm_logo_small.jpg')
     (vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(object(News), object(RecursiveIteratorIterator))
     (vendor\symfony\symfony\src\Symfony\Component\Form\Form.php:383)
  at Symfony\Component\Form\Form->setData(object(News))
     (vendor\sonata-project\admin-bundle\src\Controller\CRUDController.php:313)
  at Sonata\AdminBundle\Controller\CRUDController->editAction('9')
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\app_dev.php:29)
  at require('C:\\Users\\abel\\PhpstormProjects\\LyceeJeanMonnet\\jeanmonnet\\web\\app_dev.php')
     (vendor\symfony\symfony\src\Symfony\Bundle\WebServerBundle\Resources\router.php:42)
```

My image field in the Entity:
```
    /**
     * @ORM\Column(nullable=true)
     * @ORM\ManyToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media", cascade={"all"})
     * @ORM\JoinColumn(name="image", referencedColumnName="id")
     */
    private $image;
```
What I find strange is that doctrine to convert this field to varchar in the database, while a media is identified by the field id which is an integer.

The Admin class
```
class NewsAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        ...
        $formMapper->add('image', 'sonata_media_type', array(
            'required' => false,
            'label' => 'Image',
            'provider' => 'sonata.media.provider.image',
            'data_class'   =>  'Application\Sonata\MediaBundle\Entity\Media',
            'context'  => 'news'
        ));
        ...
    }
    ...
}
```

config.yml
```
sonata_media:
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        news:
            providers:
                - sonata.media.provider.image
            formats:
                preview:   { width: 100, quality: 100}
                small:     { width: 200, quality: 100}
                large:     { width: 600, quality: 100}
```
#### Sonata packages
```

sonata-project/admin-bundle              3.32.0 = 3.32.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.0 = 3.12.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  = 2.0.1  Cache library
sonata-project/core-bundle               3.9.1  = 3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  = 2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  = 1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.4.2  = 3.4.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  = 2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  = 1.8.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.4.1  = 3.4.1  Symfony SonataFormatterBundle
sonata-project/media-bundle              3.11.0 = 3.11.0 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.4.0  = 3.4.0  Symfony SonataNotificationBundle
sonata-project/user-bundle               4.1.1  = 4.1.1  Symfony SonataUserBundle
```

#### Symfony packages
```

symfony/monolog-bundle     v3.2.0 = v3.2.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.6 ~ v4.0.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.7.0 = v1.7.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.7.0 = v1.7.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.7.0 = v1.7.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.7.0 = v1.7.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.7.0 = v1.7.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.7.0 = v1.7.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1 = v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 ~ v3.2.0 Symfony SwiftmailerBundle
symfony/symfony            v3.4.6 ~ v4.0.6 The Symfony PHP framework
```

#### PHP version

```
PHP 7.1.13 (cli) (built: Jan  3 2018 20:04:41) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```
