### ISSUE TITLE
[Proposal] A recipe for Symfony Flex

### ISSUE THREAD

**Issue by covex-nn** [sonata-project/SonataMediaBundle#1419]
The main blocker for recipe is a `db_driver` parameter - it is required and it's possible values cannot be used without installing additional packages.

We could make that parameter optional with `no_driver` default value, like i suggested in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2708. The main goal of a default value is to pass `cache:clear` stage without errors and to make a recipe valid.

With a new driver some services like `sonata.media.manager.media` must be created, because other services depend on them. I suggest to create a new classes for that services, that will throw exceptions on usage _in runtime_ with instructions for a developer what to do next.

With a default `db_driver` we will have a recipe with default configuration for MediaBundle. This configuration will be extended by recipes for specific meta package, i.e. `sonata-project/media-orm-pack` or `sonata-project/media-phpcr-pack`. All such packages will require `sonata-project/media-bundle` and conflict with each other. Each pack recipe will contain only Entity, Document or PHPCR classes _with annotations_, that will be copied into `src` directory during installation. So, no new `maker` or `easy-extends` bundle will be required.

**Comment by kunicmarko20** [comment]
Can't we add configuration with `db_driver: orm` to the pack and then copy it from pack?

**Comment by covex-nn** [comment]
MediaBundle does not require `doctrine/doctrine-bundle`, so `db_driver: doctrine_orm` will cause an error:

> The service "sonata.media.serializer.handler.gallery" has a dependency on a non-existent service "doctrine"

**Comment by covex-nn** [comment]
A recipe for `sonata-project/media-orm-pack` will contain `db_driver: doctrine_orm`! Also `sonata-project/media-orm-pack` will require `sonata-project/media-bundle`, `doctrine/doctrine-bundle` and `doctrine/orm`. So, after `sonata-project/media-orm-pack` installation, MediaBundle will be fully functional

**Comment by kunicmarko20** [comment]
So a pack can require additional libs? Then that is it, we just create packs and we are done?

**Comment by jordisala1991** [comment]
IMO it is a great idea to just use packs

**Comment by covex-nn** [comment]
MediaBundle recipe could have it's default configuration:

```yaml
sonata_media:
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            directory: "%kernel.project_dir%/public/upload/media"
            create: false
```

And then pack recipe will have only storage configuration (and Entity/Document/PHPCR classes):

```yaml
sonata_media:
    class:
        media: App\Entity\SonataMediaMedia
        gallery: App\Entity\SonataMediaGallery
        gallery_has_media: App\Entity\SonataMediaGalleryHasMedia
    db_driver: doctrine_orm
```
