### ISSUE TITLE
Class Application\Sonata\MediaBundle\Entity\Media does not exist

### ISSUE THREAD

**Issue by divined** [sonata-project/SonataMediaBundle#1443]
### Environment
dev

#### Sonata packages
AdminBundle
DoctrineORMAdminBundle
ClassificationBundle
EasyExtendsBundle
MediaBundle
```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.35.2 3.35.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/classification-bundle     3.7.0  3.7.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.9.1  3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.0  3.6.0  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.9.0  1.9.0  Lightweight Exporter library
sonata-project/media-bundle              3.13.1 3.13.1 Symfony SonataMediaBundle

```

#### Symfony packages
composer create-project symfony/website-skeleton my-project
```
$ composer show --latest 'symfony/*'
# Put the result here.
```

#### PHP version

```
$ php -v
symfony/asset                v4.1.0             v4.1.0             Symfony Asset Component
symfony/browser-kit          v4.1.0             v4.1.0             Symfony BrowserKit Component
symfony/cache                v4.1.0             v4.1.0             Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.11            v3.4.11            Symfony ClassLoader Component
symfony/config               v4.1.0             v4.1.0             Symfony Config Component
symfony/console              v4.1.0             v4.1.0             Symfony Console Component
symfony/css-selector         v4.1.0             v4.1.0             Symfony CssSelector Component
symfony/debug                v4.1.0             v4.1.0             Symfony Debug Component
symfony/debug-bundle         v4.1.0             v4.1.0             Symfony DebugBundle
symfony/debug-pack           v1.0.5             v1.0.5             A debug pack for Symfony projects
symfony/dependency-injection v4.1.0             v4.1.0             Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.1.0             v4.1.0             Symfony Doctrine Bridge
symfony/dom-crawler          v4.1.0             v4.1.0             Symfony DomCrawler Component
symfony/dotenv               v4.1.0             v4.1.0             Registers environment variables from a .env file
symfony/event-dispatcher     v4.1.0             v4.1.0             Symfony EventDispatcher Component
symfony/expression-language  v4.1.0             v4.1.0             Symfony ExpressionLanguage Component
symfony/filesystem           v4.1.0             v4.1.0             Symfony Filesystem Component
symfony/finder               v4.1.0             v4.1.0             Symfony Finder Component
symfony/flex                 v1.0.80            v1.0.80           
symfony/form                 v4.1.0             v4.1.0             Symfony Form Component
symfony/framework-bundle     v4.1.0             v4.1.0             Symfony FrameworkBundle
symfony/http-foundation      v4.1.0             v4.1.0             Symfony HttpFoundation Component
symfony/http-kernel          v4.1.0             v4.1.0             Symfony HttpKernel Component
symfony/inflector            v4.1.0             v4.1.0             Symfony Inflector Component
symfony/intl                 v4.1.0             v4.1.0             A PHP replacement layer for the C intl extension th...
symfony/lts                  dev-master 6de50b2 dev-master 6de50b2 Enforces Long Term Supported versions of Symfony co...
symfony/maker-bundle         v1.5.0             v1.5.0             Symfony Maker helps you create empty commands, cont...
symfony/monolog-bridge       v4.1.0             v4.1.0             Symfony Monolog Bridge
symfony/monolog-bundle       v3.2.0             v3.2.0             Symfony MonologBundle
symfony/options-resolver     v4.1.0             v4.1.0             Symfony OptionsResolver Component
symfony/orm-pack             v1.0.5             v1.0.5             A pack for the Doctrine ORM
symfony/phpunit-bridge       v4.1.0             v4.1.0             Symfony PHPUnit Bridge
symfony/polyfill-ctype       v1.8.0             v1.8.0             Symfony polyfill for ctype functions
symfony/polyfill-intl-icu    v1.8.0             v1.8.0             Symfony polyfill for intl's ICU-related data and cl...
symfony/polyfill-mbstring    v1.8.0             v1.8.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.8.0             v1.8.0             Symfony polyfill backporting some PHP 7.2+ features...
symfony/process              v4.1.0             v4.1.0             Symfony Process Component
symfony/profiler-pack        v1.0.3             v1.0.3             A pack for the Symfony web profiler
symfony/property-access      v4.1.0             v4.1.0             Symfony PropertyAccess Component
symfony/property-info        v4.1.0             v4.1.0             Symfony Property Info Component
symfony/routing              v4.1.0             v4.1.0             Symfony Routing Component
symfony/security             v4.1.0             v4.1.0             Symfony Security Component
symfony/security-acl         v3.0.1             v3.0.1             Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.1.0             v4.1.0             Symfony SecurityBundle
symfony/serializer           v4.1.0             v4.1.0             Symfony Serializer Component
symfony/serializer-pack      v1.0.1             v1.0.1             A pack for the Symfony serializer
symfony/stopwatch            v4.1.0             v4.1.0             Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.2             v3.2.2             Symfony SwiftmailerBundle
symfony/templating           v4.1.0             v4.1.0             Symfony Templating Component
symfony/test-pack            v1.0.2             v1.0.2             A pack for functional testing within a Symfony app
symfony/translation          v4.1.0             v4.1.0             Symfony Translation Component
symfony/twig-bridge          v4.1.0             v4.1.0             Symfony Twig Bridge
symfony/twig-bundle          v4.1.0             v4.1.0             Symfony TwigBundle
symfony/validator            v4.1.0             v4.1.0             Symfony Validator Component
symfony/var-dumper           v4.1.0             v4.1.0             Symfony mechanism for exploring and dumping PHP var...
symfony/web-link             v4.1.0             v4.1.0             Symfony WebLink Component
symfony/web-profiler-bundle  v4.1.0             v4.1.0             Symfony WebProfilerBundle
symfony/web-server-bundle    v4.1.0             v4.1.0             Symfony WebServerBundle
symfony/webpack-encore-pack  v1.0.2             v1.0.2             A pack for Symfony Encore
symfony/yaml                 v4.1.0             v4.1.0             Symfony Yaml Component
```

## Subject

Oppening this url: /admin/sonata/media/media/list
Show this exception: Class Application\Sonata\MediaBundle\Entity\Media does not exist

```
ReflectionException:
Class Application\Sonata\MediaBundle\Entity\Media does not exist

  at vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php:197
  at ReflectionClass->__construct('Application\\Sonata\\MediaBundle\\Entity\\Media')
     (vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php:197)
  at Doctrine\Common\Persistence\AbstractManagerRegistry->getManagerForClass('Application\\Sonata\\MediaBundle\\Entity\\Media')
     (vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:284)
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getEntityManager('Application\\Sonata\\MediaBundle\\Entity\\Media')
     (vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:63)
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getMetadata('Application\\Sonata\\MediaBundle\\Entity\\Media')
     (vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:329)
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getModelIdentifier('Application\\Sonata\\MediaBundle\\Entity\\Media')
     (vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:536)
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getDefaultSortValues('Application\\Sonata\\MediaBundle\\Entity\\Media')
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:774)
  at Sonata\AdminBundle\Admin\AbstractAdmin->getFilterParameters()
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:800)
  at Sonata\AdminBundle\Admin\AbstractAdmin->buildDatagrid()
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:1335)
  at Sonata\AdminBundle\Admin\AbstractAdmin->getDatagrid()
     (vendor/sonata-project/media-bundle/src/Controller/MediaAdminController.php:69)
  at Sonata\MediaBundle\Controller\MediaAdminController->listAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:149)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:188)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:37)
```

**Comment by covex-nn** [comment]
@divined have you already created that class or you just installed all that packages?

Anyway, if you have a similar error on `/admin/sonata/classification/category/tree` url, you did not follow installation instructions: https://sonata-project.org/bundles/media/3-x/doc/reference/installation.html and https://sonata-project.org/bundles/classification/2-x/doc/reference/installation.html

Right now you can install another package `composer require sonata-project/media-orm-pack`, Symfony Flex will add classes for all MediaBundle entities with its recipe. But we do not have a recipe for ClassificationBundle yet, you must configure is manualy

**Comment by kunicmarko20** [comment]
Did you do the easy extends part of the installation tutorial?

**Comment by divined** [comment]
Yes, bin/console sonata:easy-extends:generate --dest=src SonataMediaBundle --namespace_prefix=App
used.
I have file.

But i have class in namespace: App\Application\Sonata\MediaBundle\Entity
not Application\Sonata\MediaBundle\Entity =(

**Comment by kunicmarko20** [comment]
Did you set class config in sonata media config?

```
# config/packages/sonata.yaml

sonata_media:
    # if you don't use default namespace configuration
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
```

**Comment by divined** [comment]
no, i set it in 

```
sonata_classification:
    class:
        tag: App\Application\Sonata\ClassificationBundle\Entity\Tag
        category: App\Application\Sonata\ClassificationBundle\Entity\Category
        collection: App\Application\Sonata\ClassificationBundle\Entity\Collection
        context: App\Application\Sonata\ClassificationBundle\Entity\Context
        media: App\Application\Sonata\MediaBundle\Entity\Media
```

If i use it in your way i will get error:
 The target-entity Application\Sonata\MediaBundle\Entity\Media cannot be found in 'App\Application\Sonata\Classificati  
  onBundle\Entity\Collection#media'.

**Comment by divined** [comment]
Any news?

**Comment by divined** [comment]
?

**Comment by OskarStark** [comment]
I guess the xml is invalid pointing to `Application\...` instead of `App\Application\....`

**Comment by jordangidoin** [comment]
If you have this error :

```
The target-entity Application\Sonata\MediaBundle\Entity\Media cannot be found in 'App\Application\Sonata\ClassificationBundle\Entity\Collection#media'. 
```

add to sonata_media the new category class : 

```yml
#config/packages/sonata_media.yaml

sonata_media:
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category: App\Application\Sonata\ClassificationBundle\Entity\Category
```

**Comment by onurguven** [comment]
any news?

**Comment by antismok** [comment]
I solve my problem with:
`
sonata_product:
    ...
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
`

**Comment by latheva** [comment]
Hi, I had the same on Symfony4, I've solved it by adding media class to the config.
and remember that I have **skipped** he easy-extends step _(bin/console sonata:easy-extends:generate --dest=src SonataClassificationBundle --namespace_prefix=App)_
sonata_classification:
    class:
        tag:          App\Entity\SonataClassificationTag
        category:     App\Entity\SonataClassificationCategory
        collection:   App\Entity\SonataClassificationCollection
        context:      App\Entity\SonataClassificationContext
        media: App\Application\Sonata\MediaBundle\Entity\Media

**Comment by HecFranco** [comment]
Yo tengo el mismo error: `The target-entity Application `Sonata `ClassificationBundle `Entity no se puede encontrar en'AppApplication `Sonata `MediaBundle `EntityMedia#category'.

I have the demo uploaded on my github : [https://github.com/HecFranco/Sonata-project-complete-demo](https://github.com/HecFranco/Sonata-project-complete-demo).

and this is my configuration in symfony 4.

```yaml
sonata_classification:
    class:
        category: App\Application\Sonata\ClassificationBundle\Entity\Category
        collection: App\Application\Sonata\ClassificationBundle\Entity\Collection
        context: App\Application\Sonata\ClassificationBundle\Entity\Context
        tag: App\Application\Sonata\ClassificationBundle\Entity\Tag

    admin:
        tag:
            class:        Sonata\ClassificationBundle\Admin\TagAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        category:
            class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
            controller:   SonataClassificationBundle:CategoryAdmin
            translation:  SonataClassificationBundle
        collection:
            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        context:
            class:        Sonata\ClassificationBundle\Admin\ContextAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle 
sonata_media:
    # if you don't use default namespace configuration
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false
    providers:
        image:
            resizer: sonata.media.resizer.square
```
```php
<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Sonata\DatagridBundle\SonataDatagridBundle::class => ['all' => true],
    Sonata\CoreBundle\SonataCoreBundle::class => ['all' => true],
    Sonata\BlockBundle\SonataBlockBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Sonata\AdminBundle\SonataAdminBundle::class => ['all' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Sonata\EasyExtendsBundle\SonataEasyExtendsBundle::class => ['all' => true],
    Sonata\UserBundle\SonataUserBundle::class => ['all' => true],
    App\Application\Sonata\UserBundle\ApplicationSonataUserBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Prodigious\Sonata\MenuBundle\ProdigiousSonataMenuBundle::class => ['all' => true],
    Sonata\ClassificationBundle\SonataClassificationBundle::class => ['all' => true],
    App\Application\Sonata\ClassificationBundle\ApplicationSonataClassificationBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Sonata\MediaBundle\SonataMediaBundle::class => ['all' => true],
    App\Application\Sonata\MediaBundle\ApplicationSonataMediaBundle::class => ['all' => true],
    Sonata\CacheBundle\SonataCacheBundle::class => ['all' => true],
    Sonata\SeoBundle\SonataSeoBundle::class => ['all' => true],
    Sonata\NotificationBundle\SonataNotificationBundle::class => ['all' => true],
    App\Application\Sonata\NotificationBundle\ApplicationSonataNotificationBundle::class => ['all' => true],    
];
```

Does anyone know why this could be happening?
