### ISSUE TITLE
Sonata Media Context error

### ISSUE THREAD

**Issue by Van-peterson** [sonata-project/SonataMediaBundle#1460]
#### Could not use 'sonata_type_model_list', it show an error class does not exist

```
 ->add('billScan', ModelListType::class, array('label' => 'Facture scanné'), array('context' => 'facture'))
```

**Comment by dmarkowicz** [comment]
try
```
->add('billScan', ModelListType::class, array('label' => 'Facture scanné'), array('link_parameters' => array('context' => 'facture')))
```
see https://sonata-project.org/bundles/media/master/doc/reference/media_context.html

**Comment by Van-peterson** [comment]
Thanks @dmarkowicz , It works for me.
Please how do i remove '0001' and '01' folders in 'upload/media/facture' folder ?
I want to get something like this : Z:\upload\media\facture\File_name.pdf 
Not Z:\upload\media\facture\0001\01\File_name.pdf

**Comment by dmarkowicz** [comment]
You need replace `sonata.media.generator.default` by custom generator. Then pass it to
```yml
sonata_media:
    providers:
        file:
            generator:  app.media.generator.my_custom
```
or define custom media provider service based on standard and pass custom generator there.
https://sonata-project.org/bundles/media/master/doc/reference/advanced_configuration.html

**Comment by Van-peterson** [comment]
Thanks @dmarkowicz , Please could you provide a full working custom provider for file and the settings.
Please I'm new in Sonata.
Thanks in advance.

**Comment by dmarkowicz** [comment]
```php
<?php
// src/Application/Sonata/MediaBundle/Generator/MyGenerator.php
namespace Application\Sonata\MediaBundle\Generator;

use Sonata\MediaBundle\Generator\GeneratorInterface;
use Sonata\MediaBundle\Model\MediaInterface;

class MyGenerator implements GeneratorInterface
{
    public function generatePath(MediaInterface $media)
    {
        return sprintf('%s', $media->getContext());
    }
}
```
```yaml
# services.yml
    app.media.generator.my_generator:
        class: Application\Sonata\MediaBundle\Generator\MyGenerator
```
```yaml
# config.yml
sonata_media:
    providers:
        file:
            generator:  app.media.generator.my_generator
```
For future questions please use https://stackoverflow.com/questions/tagged/sonata or #sonata on the symfony-devs slack. Issues here are for bug reporting.
