### ISSUE TITLE
Upgrading from Symfony 3.3 to 3.4 with flex broke link between Media and Classification

### ISSUE THREAD

**Issue by ksom** [sonata-project/SonataMediaBundle#1479]
Hi all !

!! RESOLVED, SEE THE FIRST COMMENT !!

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'

sonata-project/admin-bundle              3.38.2 3.39.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/classification-bundle     3.7.1  3.7.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.11.2 3.11.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.1.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.1  3.6.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.9.1  1.9.1  Lightweight Exporter library
sonata-project/media-bundle              3.15.0 3.16.1 Symfony SonataMediaBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/apache-pack          v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                v3.4.14 v4.1.6  Symfony Asset Component
symfony/browser-kit          v3.4.14 v4.1.6  Symfony BrowserKit Component
symfony/cache                v3.4.14 v4.1.6  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.14 v3.4.17 Symfony ClassLoader Component
symfony/config               v3.4.14 v4.1.6  Symfony Config Component
symfony/console              v3.4.14 v4.1.6  Symfony Console Component
symfony/css-selector         v3.4.14 v4.1.6  Symfony CssSelector Component
symfony/debug                v3.4.14 v4.1.6  Symfony Debug Component
symfony/debug-bundle         v3.4.14 v4.1.6  Symfony DebugBundle
symfony/debug-pack           v1.0.6  v1.0.6  A debug pack for Symfony projects
symfony/dependency-injection v3.4.14 v4.1.6  Symfony DependencyInjection Component
symfony/doctrine-bridge      v3.4.14 v4.1.6  Symfony Doctrine Bridge
symfony/dom-crawler          v3.4.14 v4.1.6  Symfony DomCrawler Component
symfony/dotenv               v3.4.14 v4.1.6  Registers environment variables from a .env file
symfony/event-dispatcher     v3.4.14 v4.1.6  Symfony EventDispatcher Component
symfony/expression-language  v3.4.14 v4.1.6  Symfony ExpressionLanguage Component
symfony/filesystem           v3.4.14 v4.1.6  Symfony Filesystem Component
symfony/finder               v3.4.14 v4.1.6  Symfony Finder Component
symfony/flex                 v1.0.89 v1.1.1  Composer plugin for Symfony
symfony/form                 v3.4.14 v4.1.6  Symfony Form Component
symfony/framework-bundle     v3.4.14 v4.1.6  Symfony FrameworkBundle
symfony/http-foundation      v3.4.14 v4.1.6  Symfony HttpFoundation Component
symfony/http-kernel          v3.4.14 v4.1.6  Symfony HttpKernel Component
symfony/inflector            v3.4.14 v4.1.6  Symfony Inflector Component
symfony/intl                 v3.4.14 v4.1.6  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lts                  v3      v3      Enforces Long Term Supported versions of Symfony components
Package symfony/lts is abandoned, you should avoid using it. Use symfony/flex instead.
symfony/maker-bundle         v1.6.0  v1.7.0  Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you c...
symfony/monolog-bridge       v3.4.14 v4.1.6  Symfony Monolog Bridge
symfony/monolog-bundle       v3.3.0  v3.3.0  Symfony MonologBundle
symfony/options-resolver     v3.4.14 v4.1.6  Symfony OptionsResolver Component
symfony/orm-pack             v1.0.5  v1.0.5  A pack for the Doctrine ORM
symfony/phpunit-bridge       v4.1.3  v4.1.6  Symfony PHPUnit Bridge
symfony/polyfill-apcu        v1.9.0  v1.9.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype       v1.9.0  v1.9.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-icu    v1.9.0  v1.9.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.9.0  v1.9.0  Symfony polyfill for the Mbstring extension
symfony/process              v3.4.14 v4.1.6  Symfony Process Component
symfony/profiler-pack        v1.0.3  v1.0.3  A pack for the Symfony web profiler
symfony/property-access      v3.4.14 v4.1.6  Symfony PropertyAccess Component
symfony/property-info        v3.4.14 v4.1.6  Symfony Property Info Component
symfony/routing              v3.4.14 v4.1.6  Symfony Routing Component
symfony/security             v3.4.14 v4.1.6  Symfony Security Component
symfony/security-acl         v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v3.4.14 v4.1.6  Symfony SecurityBundle
symfony/serializer           v3.4.14 v4.1.6  Symfony Serializer Component
symfony/serializer-pack      v1.0.1  v1.0.1  A pack for the Symfony serializer
symfony/stopwatch            v3.4.14 v4.1.6  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.2  v3.2.3  Symfony SwiftmailerBundle
symfony/templating           v3.4.14 v4.1.6  Symfony Templating Component
symfony/test-pack            v1.0.2  v1.0.4  A pack for functional testing within a Symfony app
symfony/thanks               v1.0.8  v1.1.0  Give thanks (in the form of a GitHub ⭐) to your fellow PHP package maintainers (not limited to ...
symfony/translation          v3.4.14 v4.1.6  Symfony Translation Component
symfony/twig-bridge          v3.4.14 v4.1.6  Symfony Twig Bridge
symfony/twig-bundle          v3.4.14 v4.1.6  Symfony TwigBundle
symfony/validator            v3.4.14 v4.1.6  Symfony Validator Component
symfony/var-dumper           v3.4.14 v4.1.6  Symfony mechanism for exploring and dumping PHP variables
symfony/web-link             v3.4.14 v4.1.6  Symfony WebLink Component
symfony/web-profiler-bundle  v3.4.14 v4.1.6  Symfony WebProfilerBundle
symfony/webpack-encore-pack  v1.0.3  v1.0.3  A pack for Symfony Encore
symfony/yaml                 v3.4.14 v4.1.6  Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.1.19 (cli) (built: Jul  6 2018 17:26:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.19, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

When upgrading from :
Symfony from 3.3 to 3.4 with flex (new directory structure)
Sonata Media from 3.9.0 to 3.15.0
Sonata Clasfification from 3.4.0 to 3.7.1

This change my database schema and remove all references between classification bundle and media bundle. I didn't find a way to make Sonata Media works with Sonata Classification.

## Steps to reproduce
Having a Sonata Media pluggued with Sonata Classification. Upgrade from 3.3 to 3.4 flex data structure.

```sh
bin/console doctrine:schema:update --dump-sql
```

## Expected results
No changes in database.

## Actual results
``` SQL
     ALTER TABLE classification__collection DROP FOREIGN KEY FK_A406B56AE25D857E;
     ALTER TABLE classification__collection DROP FOREIGN KEY FK_A406B56AEA9FDD75;
     DROP INDEX tag_collection ON classification__collection;
     DROP INDEX IDX_A406B56AE25D857E ON classification__collection;
     DROP INDEX IDX_A406B56AEA9FDD75 ON classification__collection;
     ALTER TABLE classification__collection DROP context, DROP media_id;
     ALTER TABLE classification__tag DROP FOREIGN KEY FK_CA57A1C7E25D857E;
     DROP INDEX tag_context ON classification__tag;
     DROP INDEX IDX_CA57A1C7E25D857E ON classification__tag;
     ALTER TABLE classification__tag DROP context;
     ALTER TABLE classification__category DROP FOREIGN KEY FK_43629B36727ACA70;
     ALTER TABLE classification__category DROP FOREIGN KEY FK_43629B36E25D857E;
     ALTER TABLE classification__category DROP FOREIGN KEY FK_43629B36EA9FDD75;
     DROP INDEX IDX_43629B36727ACA70 ON classification__category;
     DROP INDEX IDX_43629B36E25D857E ON classification__category;
     DROP INDEX IDX_43629B36EA9FDD75 ON classification__category;
     ALTER TABLE classification__category DROP parent_id, DROP context, DROP media_id;
```

### Some of files

```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            enum: string
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            SonataClassificationBundle: ~
            ApplicationSonataClassificationBundle: ~
            SonataMediaBundle: ~
            ApplicationSonataMediaBundle: ~
```

```yaml
# config/packages/sonata_classification.yaml
sonata_classification:
    class:
        category: App\Entity\SonataClassificationCategory
        collection: App\Entity\SonataClassificationCollection
        context: App\Entity\SonataClassificationContext
        tag: App\Entity\SonataClassificationTag
        media: App\Entity\SonataMediaMedia
```

```yaml
# config/packages/sonata_media.yaml
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    class:
        media:              App\Application\Sonata\MediaBundle\Entity\Media
        gallery:            App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category:           App\Application\Sonata\ClassificationBundle\Entity\Category
    contexts:
        default:
            providers:
                - sonata.media.provider.image
            formats: ~
        sponsor_logo:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 500 , quality: 70}
```

```php
<?php
// config/bundles.php

return [
     
    Sonata\ClassificationBundle\SonataClassificationBundle::class => ['all' => true],
    App\Application\Sonata\MediaBundle\ApplicationSonataMediaBundle::class => ['all' => true],
    App\Application\Sonata\ClassificationBundle\ApplicationSonataClassificationBundle::class => ['all' => true],
    Sonata\MediaBundle\SonataMediaBundle::class => ['all' => true],
];
```

Thanks in advance !
