### ISSUE TITLE
Incorrect extension when downloading ZIP

### ISSUE THREAD

**Issue by byhaskell** [sonata-project/SonataMediaBundle#1535]
#### Sonata packages

```
sonata-project/admin-bundle              3.45.1          = 3.45.1             The missing Symfony Admin Generator
sonata-project/block-bundle              3.14.0          = 3.14.0             Symfony SonataBlockBundle
sonata-project/cache                     2.0.1           = 2.0.1              Cache library
sonata-project/core-bundle               3.15.0          = 3.15.0             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0           = 2.4.0              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5           = 1.1.5              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.0           = 3.8.0              Symfony Sonata / Integrate Doctrine O...
sonata-project/easy-extends-bundle       2.5.0           = 2.5.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.0.0           = 2.0.0              Lightweight Exporter library
sonata-project/media-bundle              3.x-dev 115edc7 ~ dev-master d7b87b2 Symfony SonataMediaBundle
```

#### Symfony packages

```
symfony/asset                v4.2.2  = v4.2.2  Symfony Asset Component
symfony/cache                v4.2.2  = v4.2.2  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               v4.2.2  = v4.2.2  Symfony Config Component
symfony/console              v4.2.2  = v4.2.2  Symfony Console Component
symfony/contracts            v1.0.2  = v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/debug                v4.2.2  = v4.2.2  Symfony Debug Component
symfony/debug-bundle         v4.2.2  = v4.2.2  Symfony DebugBundle
symfony/dependency-injection v4.2.2  = v4.2.2  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.2.2  = v4.2.2  Symfony Doctrine Bridge
symfony/dotenv               v4.2.2  = v4.2.2  Registers environment variables from a .env file
symfony/event-dispatcher     v4.2.2  = v4.2.2  Symfony EventDispatcher Component
symfony/expression-language  v4.2.2  = v4.2.2  Symfony ExpressionLanguage Component
symfony/filesystem           v4.2.2  = v4.2.2  Symfony Filesystem Component
symfony/finder               v4.2.2  = v4.2.2  Symfony Finder Component
symfony/flex                 v1.1.8  = v1.1.8  Composer plugin for Symfony
symfony/form                 v4.2.2  = v4.2.2  Symfony Form Component
symfony/framework-bundle     v4.2.2  = v4.2.2  Symfony FrameworkBundle
symfony/http-foundation      v4.2.2  = v4.2.2  Symfony HttpFoundation Component
symfony/http-kernel          v4.2.2  = v4.2.2  Symfony HttpKernel Component
symfony/inflector            v4.2.2  = v4.2.2  Symfony Inflector Component
symfony/intl                 v4.2.2  = v4.2.2  A PHP replacement layer for the C intl extension that includes addit...
symfony/maker-bundle         v1.11.3 = v1.11.3 Symfony Maker helps you create empty commands, controllers, form cla...
symfony/options-resolver     v4.2.2  = v4.2.2  Symfony OptionsResolver Component
symfony/polyfill-intl-icu    v1.10.0 = v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0 = v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.10.0 = v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP ver...
symfony/process              v4.2.2  = v4.2.2  Symfony Process Component
symfony/profiler-pack        v1.0.4  = v1.0.4  A pack for the Symfony web profiler
symfony/property-access      v4.2.2  = v4.2.2  Symfony PropertyAccess Component
symfony/routing              v4.2.2  = v4.2.2  Symfony Routing Component
symfony/security-acl         v3.0.1  = v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.2.2  = v4.2.2  Symfony SecurityBundle
symfony/security-core        v4.2.2  = v4.2.2  Symfony Security Component - Core Library
symfony/security-csrf        v4.2.2  = v4.2.2  Symfony Security Component - CSRF Library
symfony/security-guard       v4.2.2  = v4.2.2  Symfony Security Component - Guard
symfony/security-http        v4.2.2  = v4.2.2  Symfony Security Component - HTTP Integration
symfony/stopwatch            v4.2.2  = v4.2.2  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.5  = v3.2.5  Symfony SwiftmailerBundle
symfony/templating           v4.2.2  = v4.2.2  Symfony Templating Component
symfony/translation          v4.2.2  = v4.2.2  Symfony Translation Component
symfony/twig-bridge          v4.2.2  = v4.2.2  Symfony Twig Bridge
symfony/twig-bundle          v4.2.2  = v4.2.2  Symfony TwigBundle
symfony/validator            v4.2.2  = v4.2.2  Symfony Validator Component
symfony/var-dumper           v4.2.2  = v4.2.2  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         v4.2.2  = v4.2.2  A blend of var_export() + serialize() to turn any serializable data ...
symfony/web-profiler-bundle  v4.2.2  = v4.2.2  Symfony WebProfilerBundle
symfony/web-server-bundle    v4.2.2  = v4.2.2  Symfony WebServerBundle
symfony/yaml                 v4.2.2  = v4.2.2  Symfony Yaml Component
```

#### PHP version

```
PHP 7.2.0 (cli) (built: Nov 28 2017 23:48:49) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```

## Subject

When the provider is selected "sonata.media.provider.file", it is impossible to download a zip archive.

## Steps to reproduce
**Services:**
```yaml
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
       project:
            providers:
                - sonata.media.provider.file

            formats: ~
```
**Admin Class:**
```php
$formMapper
    ->add('project',ModelListType::class, [
            'label' => $this->trans('object.project')
        ], [
            'link_parameters' => array('context' => 'project')
    ]);
```
## Expected results
File download with zip extension

## Actual results
 Invalid extensions (http://prntscr.com/mahfn3)

**Comment by byhaskell** [comment]
It was possible to solve the "problem" by adding a mim-type corresponding to the archive to the file provider. The question then is whether the archive should initially be added to the default list. You can also solve the problem by creating an alternative provider. #955 

```yaml
    providers:
        file:
            resizer: false
            service:    sonata.media.provider.file
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml', 'zip']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain', 'application/zip']
```
