### ISSUE TITLE
Length of either side cannot be 0 or negative, current size is 0x0

### ISSUE THREAD

**Issue by byhaskell** [sonata-project/SonataMediaBundle#1550]
#### Sonata packages

```
sonata-project/admin-bundle              3.45.1          = 3.45.1             The missing Symfony Admin Generator
sonata-project/block-bundle              3.14.0          = 3.14.0             Symfony SonataBlockBundle
sonata-project/cache                     2.0.1           = 2.0.1              Cache library
sonata-project/core-bundle               3.15.1          = 3.15.1             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0           = 2.4.0              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5           = 1.1.5              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.2           = 3.8.2              Symfony Sonata / Integrate Doctrine O...
sonata-project/easy-extends-bundle       2.5.0           = 2.5.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.0.1           = 2.0.1              Lightweight Exporter library
sonata-project/media-bundle              3.x-dev 865b3a0 ~ dev-master 19ce6f8 Symfony SonataMediaBundle
```

#### Symfony packages

```
symfony/asset                v4.2.3  = v4.2.3  Symfony Asset Component
symfony/cache                v4.2.3  = v4.2.3  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               v4.2.3  = v4.2.3  Symfony Config Component
symfony/console              v4.2.3  = v4.2.3  Symfony Console Component
symfony/contracts            v1.0.2  = v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/debug                v4.2.3  = v4.2.3  Symfony Debug Component
symfony/debug-bundle         v4.2.3  = v4.2.3  Symfony DebugBundle
symfony/dependency-injection v4.2.3  = v4.2.3  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.2.3  = v4.2.3  Symfony Doctrine Bridge
symfony/dotenv               v4.2.3  = v4.2.3  Registers environment variables from a .env file
symfony/event-dispatcher     v4.2.3  = v4.2.3  Symfony EventDispatcher Component
symfony/expression-language  v4.2.3  = v4.2.3  Symfony ExpressionLanguage Component
symfony/filesystem           v4.2.3  = v4.2.3  Symfony Filesystem Component
symfony/finder               v4.2.3  = v4.2.3  Symfony Finder Component
symfony/flex                 v1.1.8  = v1.1.8  Composer plugin for Symfony
symfony/form                 v4.2.3  = v4.2.3  Symfony Form Component
symfony/framework-bundle     v4.2.3  = v4.2.3  Symfony FrameworkBundle
symfony/http-foundation      v4.2.3  = v4.2.3  Symfony HttpFoundation Component
symfony/http-kernel          v4.2.3  = v4.2.3  Symfony HttpKernel Component
symfony/inflector            v4.2.3  = v4.2.3  Symfony Inflector Component
symfony/intl                 v4.2.3  = v4.2.3  A PHP replacement layer for the C intl extension that includes addit...
symfony/maker-bundle         v1.11.3 = v1.11.3 Symfony Maker helps you create empty commands, controllers, form cla...
symfony/options-resolver     v4.2.3  = v4.2.3  Symfony OptionsResolver Component
symfony/polyfill-intl-icu    v1.10.0 = v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0 = v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.10.0 = v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP ver...
symfony/process              v4.2.3  = v4.2.3  Symfony Process Component
symfony/profiler-pack        v1.0.4  = v1.0.4  A pack for the Symfony web profiler
symfony/property-access      v4.2.3  = v4.2.3  Symfony PropertyAccess Component
symfony/routing              v4.2.3  = v4.2.3  Symfony Routing Component
symfony/security-acl         v3.0.1  = v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.2.3  = v4.2.3  Symfony SecurityBundle
symfony/security-core        v4.2.3  = v4.2.3  Symfony Security Component - Core Library
symfony/security-csrf        v4.2.3  = v4.2.3  Symfony Security Component - CSRF Library
symfony/security-guard       v4.2.3  = v4.2.3  Symfony Security Component - Guard
symfony/security-http        v4.2.3  = v4.2.3  Symfony Security Component - HTTP Integration
symfony/stopwatch            v4.2.3  = v4.2.3  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.5  = v3.2.5  Symfony SwiftmailerBundle
symfony/templating           v4.2.3  = v4.2.3  Symfony Templating Component
symfony/translation          v4.2.3  = v4.2.3  Symfony Translation Component
symfony/twig-bridge          v4.2.3  = v4.2.3  Symfony Twig Bridge
symfony/twig-bundle          v4.2.3  = v4.2.3  Symfony TwigBundle
symfony/validator            v4.2.3  = v4.2.3  Symfony Validator Component
symfony/var-dumper           v4.2.3  = v4.2.3  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         v4.2.3  = v4.2.3  A blend of var_export() + serialize() to turn any serializable data ...
symfony/web-profiler-bundle  v4.2.3  = v4.2.3  Symfony WebProfilerBundle
symfony/web-server-bundle    v4.2.3  = v4.2.3  Symfony WebServerBundle
symfony/yaml                 v4.2.3  = v4.2.3  Symfony Yaml Component
```

#### PHP version

```
PHP 7.2.10 (cli) (built: Sep 13 2018 00:48:27) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

## Subject

When adding an image of any context error: "Length of either side cannot be 0 or negative, current size is 0x0".

As far as I understand, the necessary context has ceased to be accepted, which is why Imagine \ Image \ Box takes the false and cannot cut the image.

## Steps to reproduce
1. Upgrade to the latest version.
2. Add to configuration:
```
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        placeholder:
            providers:
                - sonata.media.provider.image

            formats:
                placeholder: { width: 500, height: 500, quality: 70}
                placeholder_small: { width: 50, height: 50, quality: 70}
```
3. Add to admin class:
```
 protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('placeholder', ModelListType::class, [
	                'label' => $this->trans('object.placeholder')
                ], [
	                'link_parameters' => array('context' => 'placeholder')
                ])
```
4. Try to add a picture
```
Imagine\Exception\InvalidArgumentException:
Length of either side cannot be 0 or negative, current size is 0x0

  at vendor/imagine/imagine/lib/Imagine/Image/Box.php:42
  at Imagine\Image\Box->__construct(0.0, 0.0)
     (vendor/imagine/imagine/lib/Imagine/Image/Box.php:70)
  at Imagine\Image\Box->scale(0)
     (vendor/sonata-project/media-bundle/src/Resizer/SimpleResizer.php:120)
  at Sonata\MediaBundle\Resizer\SimpleResizer->computeBox(object(Media), array('width' => 200, 'height' => false, 'quality' => 90, 'format' => 'jpg', 'constraint' => true))
     (vendor/sonata-project/media-bundle/src/Resizer/SimpleResizer.php:90)
  at Sonata\MediaBundle\Resizer\SimpleResizer->getBox(object(Media), array('width' => 200, 'height' => false, 'quality' => 90, 'format' => 'jpg', 'constraint' => true))
     (vendor/sonata-project/media-bundle/src/Resizer/SimpleResizer.php:65)
  at Sonata\MediaBundle\Resizer\SimpleResizer->resize(object(Media), object(File), object(File), 'jpeg', array('width' => 200, 'height' => false, 'quality' => 90, 'format' => 'jpg', 'constraint' => true))
     (vendor/sonata-project/media-bundle/src/Thumbnail/FormatThumbnail.php:124)
  at Sonata\MediaBundle\Thumbnail\FormatThumbnail->generate(object(ImageProvider), object(Media))
     (vendor/sonata-project/media-bundle/src/Provider/BaseProvider.php:146)
  at Sonata\MediaBundle\Provider\BaseProvider->generateThumbnails(object(Media))
     (vendor/sonata-project/media-bundle/src/Provider/FileProvider.php:167)
  at Sonata\MediaBundle\Provider\FileProvider->postPersist(object(Media))
     (vendor/sonata-project/media-bundle/src/Listener/BaseMediaEventSubscriber.php:79)
  at Sonata\MediaBundle\Listener\BaseMediaEventSubscriber->postPersist(object(LifecycleEventArgs))
     (vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:61)
  at Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent('postPersist', object(LifecycleEventArgs))
     (vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php:117)
  at Doctrine\ORM\Event\ListenersInvoker->invoke(object(ClassMetadata), 'postPersist', object(Media), object(LifecycleEventArgs), 4)
     (vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1103)
  at Doctrine\ORM\UnitOfWork->executeInserts(object(ClassMetadata))
     (vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:386)
  at Doctrine\ORM\UnitOfWork->commit(null)
     (vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:359)
  at Doctrine\ORM\EntityManager->flush()
     (vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:155)
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->create(object(Media))
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:691)
  at Sonata\AdminBundle\Admin\AbstractAdmin->create(object(Media))
     (vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php:619)
  at Sonata\AdminBundle\Controller\CRUDController->createAction()
     (vendor/sonata-project/media-bundle/src/Controller/MediaAdminController.php:46)
  at Sonata\MediaBundle\Controller\MediaAdminController->createAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:150)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:67)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
```

## Expected results
Successful image addition

## Actual results
Error: Length of either side cannot be 0 or negative, current size is 0x0

**Comment by cussack** [comment]
@greg0ire this is probably caused by 061c00d. The unspecified height is passed into `getBox()` (and probably also configured) as `false`, but the check inside the function is only against `null`. Is this intended behavior or should we allow false as well as null if the width of an image format is not specified?

**Comment by greg0ire** [comment]
That commit introduce more strictness globally, and maybe the fix was wrong in this case, and we should allow `false`.

**Comment by cussack** [comment]
@byhaskell do you have any heights configured as `false` in your formats? If so, try changing that to `null`. Does that fix it? If so, I will provide a PR today, otherwise I will need more time to investigate.

**Comment by byhaskell** [comment]
@cussack 
Sending you my sonata media config with all parameteres. I don't have false for heights. The only param with not clearly setted heights is formats for context  "project". Thanks!
```
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100, height: 100, quality: 70}
                big: { width: 500, height: 100, quality: 70}
                meta: { width: 1200, height: 1200, quality: 70}

        meta:
            providers:
                - sonata.media.provider.image

            formats:
                meta: { width: 1200, height: 1200, quality: 70}

        video_cover:
            providers:
                - sonata.media.provider.image

            formats:
                video_cover: { width: 1000, height: 1000, quality: 70}

        trailer:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                trailer:   { width: 1200, height: 1200, quality: 70}

        congratulation_example:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                example: { width: 1200, height: 1200, quality: 70}

        avatar:
            providers:
                - sonata.media.provider.image

            formats:
                avatar: { width: 100, height: 100, quality: 70}
                avatar_big: { width: 500, height: 500, quality: 70}
                avatar_small: { width: 50, height: 50, quality: 70}

        logo:
            providers:
                - sonata.media.provider.image

            formats:
                logo: { width: 100, height: 100, quality: 70}
                logo_big: { width: 500, height: 500, quality: 70}
                logo_small: { width: 50, height: 50, quality: 70}

        video_review:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                video_review: { width: 1200, height: 1200, quality: 768}

        placeholder:
            providers:
                - sonata.media.provider.image

            formats:
                placeholder: { width: 500, height: 500, quality: 70}
                placeholder_small: { width: 50, height: 50, quality: 70}

        placeholder_many:
            providers:
                - sonata.media.provider.image

            formats:
                placeholder_many: { width: 100, height: 100, quality: 70}

        project:
            providers:
                - sonata.media.provider.file

            formats: ~
```
