### ISSUE TITLE
Custom resizer options

### ISSUE THREAD

**Issue by wkwkgit** [sonata-project/SonataMediaBundle#1554]
## Feature Request

```
contexts:
   picture:
      providers:
      - sonata.media.provider.image
      formats:
       default: {width: 856, height: 560, quality: 84, format: 'jpg', resizer_options: {crop: true, watermark: path/to/watermark.jpg}}
```
Idea is to allow developers to pass some custom options for their custom resizers. I didnt find any fast ways to do it, but to implement this feature very easely from the bundle owner.

It will be very useful if you not using some things like liip_imagine.
