### ISSUE TITLE
The problem with overwriting the action lists. Symfony 4

### ISSUE THREAD

**Issue by uka127** [sonata-project/SonataMediaBundle#1572]
Hi,
I use Symfony4 and I need to overwrite and add new styles for the view: list_outer_rows_mosaic.html.twig. How can I overwrite this view?

I installed the package according to the documentation: https://sonata-project.org/bundles/media/3-x/doc/reference/installation.html

I tried to overwrite the view as in the admin sonata but it does not work. I created a structure: ```templates/bundles/SonataMediaBundle/MediaAdmin/list_outer_rows_mosaic.html.twig```

In service.yaml added:
```
admin.media:
        class: App\Application\Sonata\MediaBundle\Admin\MediaAdmin
        arguments: [~, App\Application\Sonata\MediaBundle\Entity\Media, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Media, group: Media}
```
Can someone help me solve this problem?

**Comment by kunicmarko20** [comment]
You can check this guide https://symfony.com/doc/current/bundles/override.html#templates else

https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/templates.html#configuring-templates

here you can see the config at the end of section `4.6`:

```
services:
    app.admin.post:
        class: App\Admin\PostAdmin
        calls:
            - [setTemplate, ['edit', '@App/PostAdmin/edit.html.twig']]
```

`calls` is what you want here
