### ISSUE TITLE
Resized images loose Exif-Data

### ISSUE THREAD

**Issue by philiplb** [sonata-project/SonataMediaBundle#1581]
#### Sonata packages

```
sonata-project/media-bundle
```

## Subject

Resized images loose exif data like rotation information.

## Steps to reproduce

I upload an image containing rotation information produced by the camera of a mobile device like a phone or tablet.

## Expected results

The different image formats keep the meta data like the rotation.

## Actual results

The different image formats loose the meta data like the rotation. The result is a correctly rotated original image but the different formats don't take the rotation into account anymore because the exif data is gone.

**Comment by lukepass** [comment]
Hello, this issue is still relevant. When uploading images with Exif data the reference is keeping the option and the image is rotated.
The generated thumbnails, instead, are not rotated and upside down.

Thanks.

**Comment by core23** [comment]
Can you please give some more information? E.g the used resizer and image lib (imagick, gd, ...)

**Comment by lukepass** [comment]
Yes, of course! These are my contexts:

        profile_pictures:
            providers:
                - sonata.media.provider.image

            formats:
                big:   { width: 300 , quality: 85 }

For now I resolved by rotating and removing the metadata at the device (smartphone) level. But I think that the resizer should honor the exif rotate metadata.

Do you need more information?

Thanks.

**Comment by core23** [comment]
IMHO it's a bug in https://github.com/avalanche123/Imagine, but feel free to investigate a little more to solve this issue.

**Comment by lukepass** [comment]
Following this issue: https://github.com/avalanche123/Imagine/issues/190

It seems that they included an Autorotated class which should rotate the image automatically. The problem lies in the thumbnail generation?

**Comment by core23** [comment]
It's a filter that does the rotation. You should include this in your config

**Comment by lukepass** [comment]
Could you please provide a little sample about this? How can I include a filter in the config? How is the filter called?

**Comment by wbloszyk** [comment]
https://sonata-project.org/bundles/media/3-x/doc/reference/advanced_configuration.html
```yaml
sonata_media:
    default_context: default
    admin_format:   { width: 200 , quality: 90, format: 'jpg'}
    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70, resizer: sonata.media.resizer.square}
                # You can pass through any custom option to resizer by using the resizer_options key
                icon:  { width: 32, quality: 70, resizer: your.custom.resizer, resizer_options: { custom_crop: true } }
```

**Comment by lukepass** [comment]
Thanks for the example @wbloszyk, I am already using a custom resizer in my application but I don't know where can I use the autoresizer filter in it. Thanks!

**Comment by lukepass** [comment]
Hello, the issue has been closed but the problem is still present. Thanks.

**Comment by VincentLanglet** [comment]
There was no activity during 6 months, and when I look at answers

> IMHO it's a bug in https://github.com/avalanche123/Imagine, but feel free to investigate a little more to solve this issue.

> It's a filter that does the rotation. You should include this in your config

It's seems not related to SonataMedia.

But if I'm wrong, PR is welcomed.

**Comment by florian2peaches** [comment]
sonata-project/media-bundle 4.16.0

We're using a normal jpg image, rotated on an iPhone before upload (so the rotation is just saved in the EXIF data). We then just save the image on the backend like this:
```php
       if ($providerName === null) {
            $providerName = $this->getProviderNameByFile($file);
        }

        /** @var Media $media */
        $media = $this->mediaManager->create();
        $media->setBinaryContent($file);
        $media->setContext($context->value);
        $media->setProviderName($providerName);

        foreach ($metadata as $key => $value) {
            $media->setMetadataValue($key, $value);
        }
        $this->mediaManager->save($media);

        return $media;
```
The yaml config for this part is:
```yaml
sonata_media:
  contexts:
    event:
      providers:
        - sonata.media.provider.file
        - sonata.media.provider.image
      formats:
        small: { width: 100, quality: 70 }
        medium: { width: 300, quality: 70 }
```
(no custom resizer stuff)
And indeed, the thumbnails generated by the sonata media bundle don't have the EXIF data anymore (which means they are not rotated correctly).
