### ISSUE TITLE
Referenced file is not deleted on delete media file and media image

### ISSUE THREAD

**Issue by khalil1608** [sonata-project/SonataMediaBundle#1622]
## Subject

Hello,

When I try to delete a media with the entity manager, the referenced file is not deleted. However when the media is an image, the formatted images (thumbnail_retina and retina) are deleted but not the referenced image...
My only solution today is to manually delete files with a listener who listens to the postRemove event on the Media entity...

On the BaseProvider i see :

```
public function postRemove(MediaInterface $media)
    {
        $path = $this->getReferenceImage($media);
        if ($this->getFilesystem()->has($path)) {
            $this->getFilesystem()->delete($path);
        }
    }
```
When $path returns : default/0001/01/dd6b602e4a4b89c27a1166b971ff3232d880deb2.pdf and $this->getFilesystem()->has($path) returns false
For me the path is wrong it should returns full relative url instead. Something like /var/www/project/public/default/0001/01/dd6b602e4a4b89c27a1166b971ff3232d880deb2.pdf
I don't understand how he calculates the path...

There is my sonata media config : 
```
sonata_media:
    db_driver: doctrine_orm
    default_context: default
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

        gallery_image:
            providers:
                - sonata.media.provider.image
            formats:
                thumbnail_retina: { width: 300, quality: 70 }
                retina: { width: 1920 , quality: 70}

        gallery_file:
            providers:
                - sonata.media.provider.file

    filesystem:
        local:
            directory: "%kernel.project_dir%/public/uploads/media"
            create:     true
    cdn:
        server:
            path: "/uploads/media"

```
Any ideas ?

Thank you 

#### Environment
Ubuntu

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.48.1 3.52.0 The missing Symfony Admin Generator                                                                                                                         
sonata-project/block-bundle              3.15.0 3.17.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  2.5.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.2.0  1.3.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.9.0  3.10.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.11.1 1.11.1 Lightweight Exporter library
sonata-project/media-bundle              3.20.1 3.20.1 Symfony SonataMediaBundle

```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                v4.2.7  v4.3.4  Symfony Asset Component                                                                                                                                               
symfony/browser-kit          v4.2.7  v4.3.4  Symfony BrowserKit Component
symfony/cache                v4.2.7  v4.3.4  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.26 v3.4.31 Symfony ClassLoader Component
symfony/config               v4.2.7  v4.3.4  Symfony Config Component
symfony/console              v4.2.7  v4.3.4  Symfony Console Component
symfony/contracts            v1.0.2  v1.1.6  A set of abstractions extracted out of the Symfony components
symfony/css-selector         v3.4.26 v4.3.4  Symfony CssSelector Component
symfony/debug                v4.2.7  v4.3.4  Symfony Debug Component
symfony/dependency-injection v4.2.7  v4.3.4  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.1.12 v4.3.4  Symfony Doctrine Bridge
symfony/dom-crawler          v4.2.7  v4.3.4  Symfony DomCrawler Component
symfony/dotenv               v4.2.7  v4.3.4  Registers environment variables from a .env file
symfony/event-dispatcher     v4.2.7  v4.3.4  Symfony EventDispatcher Component
symfony/expression-language  v4.2.7  v4.3.4  Symfony ExpressionLanguage Component
symfony/filesystem           v4.2.7  v4.3.4  Symfony Filesystem Component
symfony/finder               v4.2.7  v4.3.4  Symfony Finder Component
symfony/flex                 v1.2.3  v1.4.5  Composer plugin for Symfony
symfony/form                 v4.2.7  v4.3.4  Symfony Form Component
symfony/framework-bundle     v4.2.7  v4.3.4  Symfony FrameworkBundle
symfony/http-foundation      v4.2.7  v4.3.4  Symfony HttpFoundation Component
symfony/http-kernel          v4.2.7  v4.3.4  Symfony HttpKernel Component
symfony/inflector            v4.2.7  v4.3.4  Symfony Inflector Component
symfony/intl                 v4.2.7  v4.3.4  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/monolog-bridge       v4.2.7  v4.3.4  Symfony Monolog Bridge
symfony/monolog-bundle       v3.3.1  v3.4.0  Symfony MonologBundle
symfony/options-resolver     v4.2.7  v4.3.4  Symfony OptionsResolver Component
symfony/phpunit-bridge       v4.2.7  v4.3.4  Symfony PHPUnit Bridge
symfony/polyfill-apcu        v1.11.0 v1.12.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu    v1.11.0 v1.12.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn    v1.11.0 v1.12.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring    v1.11.0 v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.11.0 v1.12.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process              v4.2.7  v4.3.4  Symfony Process Component
symfony/profiler-pack        v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access      v4.2.7  v4.3.4  Symfony PropertyAccess Component
symfony/routing              v4.2.7  v4.3.4  Symfony Routing Component
symfony/security-acl         v3.0.2  v3.0.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.2.7  v4.3.4  Symfony SecurityBundle
symfony/security-core        v4.2.7  v4.3.4  Symfony Security Component - Core Library
symfony/security-csrf        v4.2.7  v4.3.4  Symfony Security Component - CSRF Library
symfony/security-guard       v4.2.7  v4.3.4  Symfony Security Component - Guard
symfony/security-http        v4.2.7  v4.3.4  Symfony Security Component - HTTP Integration
symfony/stopwatch            v4.2.7  v4.3.4  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.6  v3.2.8  Symfony SwiftmailerBundle
symfony/templating           v4.2.7  v4.3.4  Symfony Templating Component
symfony/translation          v4.2.7  v4.3.4  Symfony Translation Component
symfony/twig-bridge          v4.2.7  v4.3.4  Symfony Twig Bridge
symfony/twig-bundle          v4.2.7  v4.3.4  Symfony TwigBundle
symfony/validator            v4.2.7  v4.3.4  Symfony Validator Component
symfony/var-dumper           v4.2.7  v4.3.4  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         v4.2.7  v4.3.4  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle  v4.2.7  v4.3.4  Symfony WebProfilerBundle
symfony/yaml                 v4.2.7  v4.3.4  Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.1.25 (cli) (built: Dec 10 2018 15:19:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```
