### ISSUE TITLE
Migrate XML to PHP configuration

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#1941]
## Feature Request

Migrate all configs under: https://github.com/sonata-project/SonataMediaBundle/tree/3.x/src/Resources/config

This tool can help: https://github.com/symplify/config-transformer

Ref: https://github.com/sonata-project/SonataMediaBundle/pull/1940#discussion_r597608037

**Comment by wbloszyk** [comment]
I mean move `sonata.media.resizer.crop.class` parameter into `sonata_media.resizer`:
https://github.com/sonata-project/SonataMediaBundle/blob/9353e2fe98c0210d0fcc575120b03e78629eb11b/src/DependencyInjection/Configuration.php#L526-L555

Or instead class we can use service like:
```yaml
sonata_media:
    resizer:
        square:
            service: sonata.media.resizer.base_square # will be alias by sonata.media.resizer.square
```

Anyway move config from `xml` to `php` should be also done.
