### ISSUE TITLE
No entity manager defined for class Application\Sonata\MediaBundle\Entity\Gallery

### ISSUE THREAD

**Issue by muratbeser** [sonata-project/SonataMediaBundle#251]
I cant get the problem really, is it a configuration problem orm admin problem or sonata media bundle configuration problem ?

I think we can make a FAQ doc ?

**Comment by chidang** [comment]
add: new Application\Sonata\MediaBundle\ApplicationSonataMediaBundle() to your AppKernel.php
after that, run command line in your terminal: app/console doctrine:schema:update --force

**Comment by laokin28** [comment]
I just had this error because of a not closed comment juste before an annotation for an entity, resulting in the annotation being considered as part of the comment.
A stupid error but if it helps for others...

**Comment by seisler** [comment]
I had the same issue and it was because I wasn't writing the mapped class correctly in the command. Use doctrine:mongodb:mapping:info to see the mapped classes.

**Comment by jcRisch** [comment]
In symfony 4, adding 
`App\Application\Sonata\MediaBundle\ApplicationSonataMediaBundle::class => ['all' => true],`

in config/bundles.php solved it for me.

**Comment by anetka31** [comment]
I know it is old issue, but I had the same problem in symfony 4.2.
I have right conifiguration in config/bundles.php.

command bin/console doctrine:mapping:info returns
`  Found 6 mapped entities:

 [OK]   Sonata\MediaBundle\Entity\BaseGalleryHasMedia
 [OK]   Sonata\MediaBundle\Entity\BaseGallery
 [OK]   Sonata\MediaBundle\Entity\BaseMedia
 [OK]   App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
 [OK]   App\Application\Sonata\MediaBundle\Entity\Media
 [OK]   App\Application\Sonata\MediaBundle\Entity\Gallery
`
But when I choose label Gallery or Media  in admin panel I have error:
Class Application\Sonata\MediaBundle\Entity\Gallery does not exist

**Comment by kunicmarko20** [comment]
@anetka31 namespace is different:

`App\Application\Sonata\MediaBundle\Entity\Gallery`
`Application\Sonata\MediaBundle\Entity\Gallery`

**Comment by anetka31** [comment]
@kunicmarko20  You're right. But, what I should cheage to fix it?

**Comment by kunicmarko20** [comment]
If you followed the installation docs you should have:

```
sonata_media:
    # if you don't use default namespace configuration
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedi
```

do you have that?
