### ISSUE TITLE
Argument 2 passed to Sonata\MediaBundle\Provider\BaseVideoProvider::__construct() must be an instance of Gaufrette\Filesystem, null given

### ISSUE THREAD

**Issue by leek** [sonata-project/SonataMediaBundle#263]
I'm not sure what I'm doing wrong here -- I can't seem to get the `sonata.media.provider` tag to initiate the CompilerPass for my custom Provider. Here is my service definition:

``` yml
parameters:
    acme.media.provider.brightcove.class: Acme\MediaBundle\Provider\BrightcoveProvider

services:
    acme.media.provider.brightcove:
        class: "%acme.media.provider.brightcove.class%"
        arguments:
            - acme.media.provider.brightcove
            - ~
            - ~
            - ~
            - "@sonata.media.thumbnail.format"
            - "@sonata.media.buzz.browser"
        calls:
            - [ "setTemplates", ["SonataMediaBundle:Provider:thumbnail.html.twig", "SonataMediaBundle:Provider:view_dailymotion.html.twig"] ]
        tags:
            - { name: sonata.media.provider }
```
