### ISSUE TITLE
[RFC] Using factories to create providers

### ISSUE THREAD

**Issue by joelwurtz** [sonata-project/SonataMediaBundle#275]
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |

Currently each provider is unique and has only one service with his own configuration. The goal is to create multiple providers with same services but with different configuration.

For sample we can have 2 images providers one configured with default thumbnail service and the other one with liip thumbnail service.

Providers created are injected into the different contexts given the appropriate configuration.
# Configuration

The configuration will look like this : 

``` yaml

sonata_media:
    providers:
        image:
            factory_id:          sonata.media.provider.factory.image
            adapter:             sonata.media.adapter.image.imagick
            thumbnail:           sonata.media.thumbnail.liip_imagine
        admin_image:
            factory_id:          sonata.media.provider.factory.image
    contexts:
        my_first_context:
            providers: [image]

        my_second_context:
            providers: [image, admin_image]
```
# Factory Sample

Here is an example for a provider factory

``` php

class ImageFactory extends AbstractProviderFactory
{
    public function __construct()
    {
        # Option are configuration available when declaring a new provider
        $this->addOption('adapter', 'sonata.media.adapter.image.gd');
        $this->addOption('thumbnail', 'sonata.media.thumbnail.format');
    }

    public function createProvider(ContainerBuilder $container, $id, $config)
    {
        $providerId = 'sonata.media.provider.'.$id;

        // sonata.media.provider.base.image is the new name of sonata.media.provider.image
        $provider = $container->setDefinition($providerId, new DefinitionDecorator('sonata.media.provider.base.image'):
        //Here we replace argument of service definition with custom definition
        $provider->replaceArgument(5, new Reference($config['thumbnail']));
        $provider->replaceArgument(6, new Reference($config['adapter']));

        return $providerId;
    }
}
```

 # Factory Interface

Each factory must implements this interface

``` php

interface ProviderFactoryInterface
{
    public function createProvider(ContainerBuilder $container, $id, $config);
}
```

$id is the name of provider (image or admin_image in my sample)

ping @rande What do you think ?
