### ISSUE TITLE
Remove local storage after S3 Upload and use only S3

### ISSUE THREAD

**Issue by azr** [sonata-project/SonataMediaBundle#309]
I'm using the MediaBundle on Heroku and a container has only ~200MB of free space and everything uploaded gets deleted each time I update it.

So I created a bucket and I was pretty sure that if I used something like :

``` yml
    filesystem:
        s3: #only s3 as fs
            bucket:
            accessKey:
            secretKey:
            create:         false
```

Would do the trick just uploading the stuff on the container then on s3, but no.

I can upload an image using the admin bundle for example and it will be available for the lifetime of the slug but after updating or restarting it the files get lost.

Do you have any idea about how to 'fix' that ?

Edit: 
That would be awesome to be able to use [Browser Uploads to S3 using HTML POST Forms](http://aws.amazon.com/articles/1434?_encoding=UTF8&jiveRedirect=1) 

http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html
