### ISSUE TITLE
Attach an image to an object/entity with Sonata-AdminBundle

### ISSUE THREAD

**Issue by Birmania** [sonata-project/SonataMediaBundle#34]
Hello (back)

I have the same problem than this person :
https://github.com/sonata-project/SonataMediaBundle/issues/10

Here is my code :
## 

->add('picturesymbol', array(), array('edit' => 'list', 'link_parameters' => array('context' => 'symbols')))
## 

Here is my context :
## 

```
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        symbols:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
```
## 

Here is the code in my entity :
## 

```
/**
 * @var string $picturesymbol
 *
 * @ORM\Column(name="picturesymbol", type="string", length=100, nullable=false)
 * @Assert\File(maxSize="6000000")
 */
private $picturesymbol;
```
## 

Objective : With Sonata Admin-Bundle, go in "link_add" to add a new Symbol. This symbol is composed by :
-idsymbol
-namesymbol
-descriptionsymbol
-picturesymbol

I would like to add a picture to my symbol at his creation (It's why I install MediaBundle).

I try to change the code :
## 

->add('picturesymbol', array(), array('edit' => 'list', 'link_parameters' => array('context' => 'symbols')))
## 

by :
## 

->add('picturesymbol', 'file', array(), array('edit' => 'list', 'link_parameters' => array('context' => 'symbols')))
## 

but when I submit, I obtain serialization error (So I guess I am wrong when writing it like this).

Have you got some idea ?
Thanks again

P.S : I work on Symfony 2 with Admin Bundle
