### ISSUE TITLE
"Format" combo box update when adding/editing the gallery

### ISSUE THREAD

**Issue by lightglitch** [sonata-project/SonataMediaBundle#449]
When you change the context on the gallery form the "Format" combo box should be updated with correct value for the chosen context.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @lightglitch

**Comment by stivenllupa** [comment]
@core23 This issue is still active. When creating a gallery after changing the context formats are not updated to the correct context, they are still the values against the context they were generated with in the first place.

**Comment by core23** [comment]
Can you provide a PR for this @stivenllupa ?

**Comment by Chrisvore** [comment]
When in admin, try to edit a gallery by changing the context. You need to have different contexts set in your config. The format is supposed to update with the new context value.

```
sonata_media:
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 108 , height : 49 , quality: 90}
                big:   { width: 1088 , height : 493 , quality: 90}

        user:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 80 , height : 80 , quality: 80}
                big:   { width: 250 , height : 250 , quality: 90}

        cms:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 300 , height : 70 , quality: 80}
                big:   { width: 1024 , height : 768 , quality: 90}

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
```

With this configuration, when I select cms, I still have default_big and default_small in format field like shown in the image. The correct values would be cms_small and cms_big.

![image](https://cloud.githubusercontent.com/assets/10241898/23468913/619cf564-fea2-11e6-8e49-d305441cee1a.png)

The workaround gave by @stivenllupa on https://github.com/sonata-project/SonataMediaBundle/issues/575 seems to not work anymore (I am still trying to make it work).
