### ISSUE TITLE
Custom resizer inside context format

### ISSUE THREAD

**Issue by xaben** [sonata-project/SonataMediaBundle#465]
It would be nice to have the ability to set a custom resizer inside the format settings. If one is not set the default resizer from the provider is fetched.

I can work on a PR, if such a feature is welcomed.

```
somecontext:
    formats:
        small: { width: 150 , quality: 95, resizer: acme.custom.resizer}
        big: { width: 150 , quality: 95}
```
