### ISSUE TITLE
Twig helpers are not retrieving context for galleries

### ISSUE THREAD

**Issue by lologhi** [sonata-project/SonataMediaBundle#489]
Hi !
When trying to use the media helper on a gallery :
```Twig
{% media news.images, 'News_home' %}
```
I get this nice error : The image format "default_News_home" is not defined.
This was well configured :
```YAML
News:
    providers:
        - sonata.media.provider.image
    formats:
        home:  { width: 400 , quality: 70}
```

In Sonata\MediaBundle\Provider\BaseProvider.php, I can find this :
```
$baseName = $media->getContext().'_';
if (substr($format, 0, strlen($baseName)) == $baseName) {
    return $format;
}
return $baseName.$format;
```
Called by Sonata\MediaBundle\Twig\Extension\MediaExtension.php
```
$format = $provider->getFormatName($media, $format);
```

So I'm wondering if the getContext() of a Gallery is working... In my database, I can see that the medias linked to my gallery have the News context.

Thanks !
