### ISSUE TITLE
MediaBundle integrates with LiipImage

### ISSUE THREAD

**Issue by hoannv** [sonata-project/SonataMediaBundle#520]
After integrating MediaBundle with LiipImage http://sonata-project.org/bundles/media/master/doc/reference/extra.html#liip-imagine-bundle-integration, there is an exception in sonataAdmin backend. Pls help me find the reason.

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "_imagine_admin" as such route does not exist.") in SonataMediaBundle:MediaAdmin:list_custom.html.twig at line 21.

here are my configuration

```
sonata_media:
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    default_context: school
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        school:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.file
            formats:
                logo: { width: 240, height: 120, quality: 100}
                banner: { width: 960, height: 300, quality: 100 }
    cdn:
        server:
            path: http://application.com/
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
    providers:
        image:
            thumbnail:  sonata.media.thumbnail.liip_imagine
        file:
            thumbnail:  sonata.media.thumbnail.liip_imagine
        youtube:
            thumbnail:  sonata.media.thumbnail.liip_imagine
        dailymotion:
            thumbnail:  sonata.media.thumbnail.liip_imagine

liip_imagine:
    filter_sets:
        school_logo:
            quality: 100
            controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
            filters:
                thumbnail: { size: [240, 120], mode: outbound }
        school_banner:
            quality: 100
            controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
            filters:
                thumbnail: { size: [960, 300], mode: outbound }
```
