### ISSUE TITLE
Question. Why my upload path is so??

### ISSUE THREAD

**Issue by desarrolla2** [sonata-project/SonataMediaBundle#560]
Hi.

I have sonata admin and sonata media bundles working fine, so i have a dude.

I have next configuration:

``` json
        "sonata-project/admin-bundle": "2.3.*@dev",                                 │
        "sonata-project/media-bundle": "2.3.*@dev",   
```

and 

``` yml
sonata_media:
# other stuffs
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/media
            create:     true
```

My project is uploading images to this path `web/media/default/0001/01/`.

Why is necessary use `0001` and `01` folders and what is their meaning?

Regards!
