### ISSUE TITLE
Excel Files (.xlsx) returns as Zip files

### ISSUE THREAD

**Issue by dTHQb** [sonata-project/SonataMediaBundle#588]
The issue that I have is when you upload a .xlsx file and you download the entity through the download path created by the sonata media bundle, then it returns a zip file named {filename}.xlsx

When I look through the Configuration in the DependancyInjection folder then in the addProvidersSection function we see

```
private function addProvidersSection(ArrayNodeDefinition $node)
    {
        $node
            ->children()
                ->arrayNode('providers')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('file')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('service')->defaultValue('sonata.media.provider.file')->end()
                                ->scalarNode('resizer')->defaultValue(false)->end()
                                ->scalarNode('filesystem')->defaultValue('sonata.media.filesystem.local')->end()
                                ->scalarNode('cdn')->defaultValue('sonata.media.cdn.server')->end()
                                ->scalarNode('generator')->defaultValue('sonata.media.generator.default')->end()
                                ->scalarNode('thumbnail')->defaultValue('sonata.media.thumbnail.format')->end()
                                ->arrayNode('allowed_extensions')
                                    ->prototype('scalar')->end()
                                    ->defaultValue(array(
                                        'pdf', 'txt', 'rtf',
                                        'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx',
                                        'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb',
                                        'csv',
                                        'xml',
                                    ))
                                ->end()
                                ->arrayNode('allowed_mime_types')
                                    ->prototype('scalar')->end()
                                    ->defaultValue(array(
                                        'application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain',
                                        'application/excel', 'application/msword', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint',
                                        'application/vnd.ms-powerpoint', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.graphics', 'application/vnd.oasis.opendocument.presentation', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.chart', 'application/vnd.oasis.opendocument.formula', 'application/vnd.oasis.opendocument.database', 'application/vnd.oasis.opendocument.image',
                                        'text/comma-separated-values',
                                        'text/xml', 'application/xml',
                                        'application/zip', // seems to be used for xlsx document ...
                                    ))
                                ->end()
                            ->end()
                        ->end()
```

I tried to override the config so that it does not contain the application/zip mime type with

```
providers:
        file:
            service:    sonata.media.provider.file
            resizer:    false
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/excel', 'application/msword']
```

but it still defaults to application/zip because it still returns a zip file.

Does anybody know how to resolve this?

My full config is

```
sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 75, height: 75, quality: 90 }
                medium: { width: 150, height: 150, quality: 80 }
                large: { width: 1280, height: 1024, quality: 70 }
        
        rfq_document:
            providers:
                - sonata.media.provider.file
        
            formats:
                reference: { quality: 100 }
                
        rfq_picture_temp:
            providers:
                - sonata.media.provider.image
                
            formats:
                small: { width: 75, height: 75, quality: 90 }
                medium: { width: 150, height: 150, quality: 80 }
                large: { width: 1280, height: 1024, quality: 70 }
                
        user_picture_temp:
            providers:
                - sonata.media.provider.image
                
            formats:
                small: { width: 50, height: 50, quality: 100 }
                medium: { width: 90, height: 90, quality: 90}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
          
    providers:
        file:
            service:    sonata.media.provider.file
            resizer:    false
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/excel', 'application/msword']
```

Thanks
