### ISSUE TITLE
Creating context in compiler pass, images won't upload into respective formats

### ISSUE THREAD

**Issue by jrdnrc** [sonata-project/SonataMediaBundle#619]
Hi,

I've tried adding a media context, as shown in the following code:

``` php
public function process(ContainerBuilder $container)
{
    $contextPool = $container->getDefinition('sonata.media.pool');

    $contextName = 'testimonial';
    $formats = [
        $contextName . '_standard' => [
            'width' => 200,
            'quality' => 70,
            'height' => false,
            'format' => 'jpg',
            'constraint' => true
        ]
    ];

    $download = [
        'strategy' => 'sonata.media.security.superadmin_strategy',
        'mode'     => 'http'
    ];

    $providers = ['sonata.media.provider.image'];

    $contextPool->addMethodCall('addContext', [$contextName, $providers, $formats, $download]);
}
```

However, when an image is uploaded, it only uploads to the full size and a thumbnail - the `standard` context does not appear. When I create the configuration in YAML, it works as expected:

``` yml
sonata_media:
    # ...
    contexts:
        # ...
        testimonial:
            providers:
                - sonata.media.provider.image
            formats:
                standard: { width: 500, quality: 75 }
```

Any ideas as to why this may be the case?

I did notice the hack line `$pool->addMethodCall('__hack__', $config);` here:
https://github.com/sonata-project/SonataMediaBundle/blob/master/DependencyInjection/SonataMediaExtension.php#L102

Not entirely sure of the purpose of that, but I tried copying it just in case - as expected, results in an error that the method cannot be found. Why is that not the case within the bundle extension?

Thanks
