### ISSUE TITLE
Empty list after uploading

### ISSUE THREAD

**Issue by robhunt3r** [sonata-project/SonataMediaBundle#643]
When I upload an image, the file is uploaded and shown at upload directory but when I go to `/admin/sonata/media/media/list` there's one empty row with a checkbox, so I think sonata knows that there's an element but nothing is shown, no name, no description, no size... All empty.

I'm using PHPCR with some PR fixes #638 and #637 in order to make PHPCR work with this bundle.

here's my config

```yaml
sonata_media:
    db_driver:       doctrine_phpcr #doctrine_phpcr # | doctrine_mongodb
    default_context: default
    class:
        media: Application\Sonata\MediaBundle\PHPCR\Media
        gallery: Application\Sonata\MediaBundle\PHPCR\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\PHPCR\GalleryHasMedia
    contexts:
        default:  # the default context is mandatory
            download:
                mode: http # X-Sendfile | http
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100, quality: 100}
                big:   { width: 970 , quality: 100}

    cdn:
        # define the public base url for the uploaded media
        server:
            #path:      %sonata_media.cdn.host%
            path:       /uploads/media

    filesystem:
        # define where the uploaded file will be stored
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

    providers:
        # ...
        file:
            # the resizer must be set to false, otherwhise this can delete icon files from the fs
            resizer:    false
        image:
           thumbnail: sonata.media.thumbnail.format          # default value
#           thumbnail: sonata.media.thumbnail.consumer.format # can be used to dispatch the resize action to async task
#            thumbnail: sonata.media.thumbnail.liip_imagine    # use the LiipImagineBundle to resize the image
        vimeo:
            thumbnail: sonata.media.thumbnail.format          # default value
#           thumbnail: sonata.media.thumbnail.consumer.format # can be used to dispatch the resize action to async task
#           thumbnail: sonata.media.thumbnail.liip_imagine    # use the LiipImagineBundle to resize the image
        youtube:
            thumbnail: sonata.media.thumbnail.format          # default value
#           thumbnail: sonata.media.thumbnail.consumer.format # can be used to dispatch the resize action to async task
#           thumbnail: sonata.media.thumbnail.liip_imagine    # use the LiipImagineBundle to resize the image
        dailymotion:
            thumbnail: sonata.media.thumbnail.format          # default value
#           thumbnail: sonata.media.thumbnail.consumer.format # can be used to dispatch the resize action to async task
#           thumbnail: sonata.media.thumbnail.liip_imagine    # use the LiipImagineBundle to resize the image

    pixlr:
        enabled:  false
        referrer: Demo - Sonata Project

    resizer:
        simple:
#            mode:  outbound
            mode:  inset
doctrine_phpcr:
    odm:
        auto_mapping: true
        mappings:
            ApplicationSonataMediaBundle:
                prefix: Application\Sonata\MediaBundle\PHPCR
```
![captura de pantalla de 2014-10-18 17 25 27](https://cloud.githubusercontent.com/assets/5111603/4690132/01974096-56db-11e4-80c9-433cf6d09be2.png)
