### ISSUE TITLE
Initialize PHPCR tree for Media/Gallery

### ISSUE THREAD

**Issue by robhunt3r** [sonata-project/SonataMediaBundle#644]
This issue comes from here https://github.com/sonata-project/SonataMediaBundle/issues/643#issuecomment-59895783 

Research has led me to the solution. As I said in the above comment, there were nothing inside logs but I found that doctrine was performing a `SELECT` for `/cms/gallery-has-media` path when creating a Gallery returning `impossible WHERE noticed after reading const tables` because it would return FALSE every time, I've changed `Sonata\MediaBundle\PHPCR\BaseGalleryRepository` in order to get a good path for Gallery (`/cms/gallery`) which makes more sense than `gallery-has-media`.

```php
<?php

namespace Sonata\MediaBundle\PHPCR;

use Doctrine\ODM\PHPCR\DocumentRepository;
use Doctrine\ODM\PHPCR\Id\RepositoryIdInterface;

class BaseGalleryRepository extends DocumentRepository implements RepositoryIdInterface
{
    public function generateId($document, $parent = null)
    {
        return '/cms/gallery/'  . uniqid();
    }
}
```

But again the same problem, there wasn't any `/cms/gallery` path, because this bundle is not initializing the PHPCR nodes, `/cms/media` was initialized by `SymfonyCmfMediaBundle` which I forget I had.

So I initialized path with my own `GenericInitializer` and everything works as wanted.

```yaml
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        tags:
            - { name: doctrine_phpcr.initializer }
        arguments: ['FooBarBundle', ['/cms/gallery']]
```
The solution for this issue is create an initializer for PHPCR inside the bundle itself without depending on SymfonyCmfMediaBundle being used for `/cms/media` (and gallery which doesn't exists)

Want to try out the changes? https://github.com/robhunt3r/SonataMediaBundle remember to initialize the paths (I did outside forked bundle for now)
