### ISSUE TITLE
Problem with metadatas while serializing a media

### ISSUE THREAD

**Issue by Pierstoval** [sonata-project/SonataMediaBundle#671]
Hello everyone,
 
I'm trying to serialize a media by NOT using sonata api routing. I do not want to use the original api routing because I have made an "api generator" which uses a "/" syntax (like a "dot-syntax" but for an url) to retrieve datas recursively through an object.
 
But the problem is not in this use, it is in the default behavior of the Media Bundle when we want to serialize any Media.
 
My Media class is in the default `Application\Sonata\MediaBundle\Entity\Media` namespace.
I want to serialize a media in 2 ways : directly, it means I make a direct call to the repository from a controller, to get the object, and then I send it into the `$this->view($datas);` method while inside a controller extending `FOSRestController`, like this: 

```php

class ApiController extends FOSRestController
{
    /**
     * @Route("/test")
     * @Method({"GET"})
     */
    public function testAction(Request $request) {
        $obj = $this->getDoctrine()->getRepository('ApplicationSonataMediaBundle:Media')->find(1);
        return $this->view($obj);
    }
}
```

And the second way is to retrieve it from a `ManyToOne` relationship, for example in an `Article` class, which have a `media` relationship. It's a basic way, because it's simply sent to the serializer the same way as the first method.
 
But the problem is the following:

The JSON I get is this kind :
```json
{
    "name": "icon.png",
    "enabled": false,
    "provider_name": "sonata.media.provider.image",
    "provider_status": 1,
    "provider_reference": "41b473f04ef4780c5bd4aa4bfcb3d6754a895438.png",
    "provider_metadata": {
        "filename": "icon.png"
    },
    "width": 128,
    "height": 128,
    "context": "icons",
    "updated_at": "2014-11-29T23:37:36+0100",
    "created_at": "2014-11-29T23:37:36+0100",
    "content_type": "image/png",
    "size": 15150,
    "gallery_has_medias": [

    ],
    "id": 1,
    "url": "/uploads/media/icons/0001/01/41b473f04ef4780c5bd4aa4bfcb3d6754a895438.png"
}
```
 
I **DO NOT** want all these datas. In fact, I only need width, height, id, name and url (url is added by a listener, so it's added dynamically and it's not in the mapping).
 
So, I tried using `Annotations`, I tried modifying the default `Entity.Media.xml` in the `src/Application/Sonata/MediaBundle/Resources/config/serializer` directory, I tried deleting this file and adding a YML one, I tried to change this in the serializer metadata configuration like this:

```yaml
#app/config.yml
jms_serializer:
    metadata:
        directories:
            application_sonata_media:
                namespace_prefix: "Application\\Sonata\\MediaBundle"
                path: "@ApplicationSonataMediaBundle/Resources/config/serializer"
            sonata_media:
                namespace_prefix: "Sonata\\MediaBundle"
                path: "@ApplicationSonataMediaBundle/Resources/config/serializer"
```

Even when cleaning the cache after each modification, I never could change the mapping for this entity, and this is kind of a problem for me. My API will be probably handling many requests, including a huge cache system, so dividing these datas by 2 or 3 by removing useless datas is primordial. More important : personal will to get over this problem is primary :laughing: 
 
Does anyone have this problem ? Did I make a mistake in specifying my serialization mapping for this entity ?

**Comment by srascar** [comment]
@Pierstoval , 
It seems that the problem comes from JMSSerializerBundle.
When it parse your entity meta, it will start with the highest parent. 
In our case, Sonata\MediaBundle\Model\Media. 
The problem is, it add meta for a field but does not remove it from the list 
even if it is not exposed in your child entity.
To fix your problem, you might need to overwrite meta of Sonata\MediaBundle\Model\Media, not 
Application\Sonata\MediaBundle\Entity\Media.

**Comment by paq85** [comment]
@srascar is correct. Thank you @srascar .

In my case this was the solution:

```yaml
jms_serializer:
  metadata:
    directories:
      SonataMediaBundle:
        namespace_prefix: "Sonata\\MediaBundle"
        path: "@PaqGameBundle/Resources/config/serializer/sonata"
```

```yaml
Sonata\MediaBundle\Model\Media:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [api]
    copyright:
      type: string
      expose: true
      groups: [api]
```

And I now get

```json
image: {
copyright: "Someone",
id: 1
}
```
