### ISSUE TITLE
[proposal] add default resizer and default resizer adapter

### ISSUE THREAD

**Issue by hanovruslan** [sonata-project/SonataMediaBundle#700]
for now any kind of media providers works with GD resizer adapter by default so if you want to switch to imagick for example you need to add some overcomplicated lines into config like

```
sonata_media:
    # ... 
    providers:
        vimeo:
            resizer: some_bundle_config_path.resizer.simple
        youtube:
            resizer: some_bundle_config_path.resizer.simple
        dailymotion:
            resizer: some_bundle_config_path.resizer.simple
        image:
            resizer: some_bundle_config_path.resizer.simple
            adapter: sonata.media.adapter.image.imagick
```
also in some_bundle config
```
services:
    some_bundle_config_path.resizer.simple:
        class: %sonata.media.resizer.simple.class%
        arguments:
            - @sonata.media.adapter.image.imagick
            - %sonata.media.resizer.square.adapter.mode%
            - @sonata.media.metadata.proxy
```

what if just add some default resizer and resizer adapter (config yaml and Configuration processor) in purpose to simplify this feature to this by config lines like these

```
sonata_media:
    adapters:
        default: sonata.media.adapter.image.imagick
    resizers:
        default:  sonata.media.resizer.simple # sonata.media.resizer.square or some_bundle_config_path.some_resizer
```
