### ISSUE TITLE
There is no main category related to context, Upload

### ISSUE THREAD

**Issue by fofiedelly** [sonata-project/SonataMediaBundle#707]
Hi all, Thank you for this magnific Bundle, i've an issue. 
my code worked well there are few days, i've upload it on the server an run my composer install. But since this morning i could'nt upload any image more. I don't know if it's a compatibility problem or not because i've change the version of some bundles. 
I got the error:
```html
There is no main category related to context: annonce 
```
**my composer.json look like this**

```json 
"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.3.6",
        "doctrine/orm": "2.3.*",
        "doctrine/doctrine-bundle": "~1.3@dev",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.5.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",

        "gregwar/captcha-bundle": "dev-master",

        "friendsofsymfony/message-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "dev-master",

        "jms/security-extra-bundle": "dev-master",
        "coresphere/console-bundle": "dev-master",

        "knplabs/knp-paginator-bundle": "~2.4",
        "lunetics/locale-bundle": "2.2.*",
        "genemu/form-bundle": "2.2",
        "jms/serializer-bundle": "~0.11",
        "jms/i18n-routing-bundle": "~1.1",
        "sonata-project/core-bundle": "~2.2@dev",
        "sonata-project/admin-bundle": "~2.3",
        "sonata-project/easy-extends-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "~2.3@dev",
        "sonata-project/datagrid-bundle":"~2.2@dev",
        "sonata-project/classification-bundle":"~2.3@dev",
        "sonata-project/media-bundle": "~2.3",

        "hwi/oauth-bundle": "0.4.*@dev",
        "cocur/slugify": "~1.0",
        "stof/doctrine-extensions-bundle": "~1.1",
        "friendsofsymfony/elastica-bundle": "3.0.*",
        "white-october/pagerfanta-bundle": "~1.0",
        "lunetics/locale-bundle": "2.2.*"
       

    }
```
**And my config.yml is really the same like in the doc, just that i added a new context**
```yaml
sonata_media:
    default_context: default 
    db_driver: doctrine_orm
    class:
        media:              Application\Sonata\MediaBundle\Entity\Media
        gallery:            Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Application\Sonata\MediaBundle\Entity\GalleryHasMedia

    providers:
            image:
                service: sonata.media.provider.image
                resizer: sonata.media.resizer.square
                allowed_extensions: ['jpg', 'png', 'jpeg']
                allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']
    contexts:
        default:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file  
            formats:
                #small: { width:100,height:100, quality:70 }
                #big: { width:250, quality:70 }
                mobile: { width:50, height:50, quality:40 }
                to_small: { width:50, height:50, quality:70 }
                small: { width:170 , height:160, quality:90}
                listing: { width: 170, height: 120, quality: 90 }
                big: { width:300 ,quality:90 }
                bigger: { width: 600, quality:80 }
            
        annonce:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                mobile: { width:50, height:50, quality:40 } 
                to_small: { width:50, height:50, quality:70 }
                small: { width:170 , height:160, quality:90}
                listing: { width: 170, height: 120, quality: 90 }
                big: { width:300 ,quality:90 }
                bigger: { width: 600, quality:80 }
    cdn:
        server:
            path: /siteweb/web/uploads/media
    filesystem:
        local:
            directory: %kernel.root_dir%/../web/uploads/media
            create: false
```
**What could be the probleme of this issue?** 
```
CRITICAL - Uncaught PHP Exception RuntimeException:
 "There is no main category related to context: annonce" 
at /var/www/html/siteweb/vendor/sonata-project/media-bundle/Listener/ORM/MediaEventSubscriber.php line 82
