### ISSUE TITLE
MediaBundle with AWS S3 - can´t find the Bucket

### ISSUE THREAD

**Issue by TimoFrenzel** [sonata-project/SonataMediaBundle#717]
https://groups.google.com/forum/#!msg/sonata-users/a3FwVmKykOc/E3_HpVftJrYJ
https://groups.google.com/forum/#!topic/sonata-devs/o2QmXNT9u9s

"The SonataMediaBundle now work with the AWS SDK version load."

I do not think so.
I have just installed the latest version. (php composer.phar update aws / aws-sdk-php)

The configuration is the same.

Furthermore, I get the message: The Configured bucket "s3.MY_BUCKET" does not exist.

in vendor / KnpLabs / gaufrette / src / Gaufrette / adapter / AwsS3.php line at 244th

KnpLabs / gaufrette -> dev-master / 0.2.x-dev
aws / aws-sdk-php -> dev-master / 2.7.x-dev

Symfony: 2.6.4
Sonata: Master

This ist my config.yml

``` yaml
sonata_media:
    # if you don't use default namespace configuration
#    class:
#        media: MyVendor\MediaBundle\Entity\Media
#        gallery: MyVendor\MediaBundle\Entity\Gallery
#        gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.image
#                - sonata.media.provider.file
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
            formats:
                small: { width: 100 , quality: 90}
                medium: { width: 500 , quality: 90}
                big:   { width: 1000 , quality: 90}
    cdn:
            server:
                path: https://MYBUCKET # http://media.sonata-project.org/
                #path: /uploads/media # http://media.sonata-project.org/
    providers:
            image:
                service:    sonata.media.provider.image
                resizer:    sonata.media.resizer.simple # sonata.media.resizer.square
                filesystem: sonata.media.filesystem.s3
                cdn:        sonata.media.cdn.server
                generator:  sonata.media.generator.default
                thumbnail:  sonata.media.thumbnail.format
                allowed_extensions: ['jpg', 'png', 'jpeg', 'gif']
                allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png', 'image/gif']
#            file:
#                service:    sonata.media.provider.file
#                resizer:    false
#                filesystem: sonata.media.filesystem.s3
#                cdn:        sonata.media.cdn.server
#                generator:  sonata.media.generator.default
#                thumbnail:  sonata.media.thumbnail.format
#                allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml']
#                allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain']
#            youtube:
#                service:    sonata.media.provider.youtube
#                resizer:    sonata.media.resizer.simple
#                filesystem: sonata.media.filesystem.s3
#                cdn:        sonata.media.cdn.server
#                generator:  sonata.media.generator.default
#                thumbnail:  sonata.media.thumbnail.format
#                html5: false
#            dailymotion:
#                service:    sonata.media.provider.dailymotion
#                resizer:    sonata.media.resizer.simple
#                filesystem: sonata.media.filesystem.s3
#                cdn:        sonata.media.cdn.server
#                generator:  sonata.media.generator.default
#                thumbnail:  sonata.media.thumbnail.format
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
        s3:
            bucket: %xxx.s3.bucket%
            accessKey: %xxx.s3.key%
            secretKey: %xxx.s3.secret%
            create: false
            region: %xxx.s3.region%
            storage: standard
            acl: public
            #encryption:
            cache_control: max-age=86400
    buzz:
            connector:  sonata.media.buzz.connector.file_get_contents
```

Thx Timo
