### ISSUE TITLE
Wrong width/height attributes in HTML while using sonata.media.resizer.square

### ISSUE THREAD

**Issue by mvhirsch** [sonata-project/SonataMediaBundle#751]
While using sonata.media.resizer.square I'll get wrong width and height attributes in HTML.

My source pictures size is: _400x300px_
My target size is: _100x100px_

So I specify in my sonata_media configuration:

```
sonata_media:
    my_context:
        providers:
            - sonata.media.provider.image

        formats:
            my_size: { width: 100, height: 100, quality: 95 }

    providers:
        image:
            resizer: sonata.media.resizer.square
```

It will correctly resize my picture to the desired size of _100x100px_.
Then I will render it with:

```
{% media my_image.media, 'my_size' %}
```

Now weird things happen: the images _src_ is correct, but width/height will get _300_ in each, e.g.:

```
<img width="300" height="300" src="path/to/image_my_size.jpeg" title="image.jpg" alt="image.jpg">
```

Doing some code debugging, I spotted [the problem in this function](https://github.com/sonata-project/SonataMediaBundle/blob/2.3.1/Resizer/SquareResizer.php#L102-L115)

After commenting out the marked lines, it just works as expected (width=100, height=100).

---

I'm using SonataMediaBundle 2.3.1 on PHP 5.6.7 / Fedora Linux
