### ISSUE TITLE
Json Type with Doctrine 

### ISSUE THREAD

**Issue by diskomarc** [sonata-project/SonataMediaBundle#771]
Hi, 
I wanted to try your bundle doctrine and returns an error when I put the scheme to date, saying that the type "json" does not exist.

https://github.com/sonata-project/SonataMediaBundle/blob/master/Resources/config/doctrine/BaseMedia.orm.xml#L17

**Comment by rande** [comment]
As stated in the documentation, you need to enable the json extension:

```
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~

    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
```

https://sonata-project.org/bundles/media/2-2/doc/reference/installation.html
