### ISSUE TITLE
Select media provider doesn't appear when clicking add new media

### ISSUE THREAD

**Issue by Hoannv** [sonata-project/SonataMediaBundle#814]
My composer.json:
```
"sonata-project/admin-bundle": "2.3.*@dev",
"sonata-project/doctrine-orm-admin-bundle": "2.3.*@dev",
"sonata-project/media-bundle": "2.3.*@dev",
"sonata-project/user-bundle": "2.2.*@dev",
"sonata-project/intl-bundle": "2.2.*@dev",
```
My form: 
```
$formMapper
     ->add('thumbnail', 'sonata_type_model_list',
           array(
               'btn_delete' => false,
               'required'   => true
           ),
           array(
               'link_parameters' => array(
                    'context' => 'activity'
               )
           )
     );
```

My context config:
```
contexts:
        activity:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.youtube
            formats:
```
When I click add new button: 
![screenshot from 2015-07-17 23 37 45](https://cloud.githubusercontent.com/assets/1846777/8752193/f50b3336-2cdc-11e5-8f0d-97012096d372.png)

No select media provider appears:
![screenshot from 2015-07-17 23 39 41](https://cloud.githubusercontent.com/assets/1846777/8752240/36470e74-2cdd-11e5-9a6f-f54a1a02ba62.png)

I can't upload pdf.
