### ISSUE TITLE
Check whether the model classes exists

### ISSUE THREAD

**Issue by pyrech** [sonata-project/SonataMediaBundle#818]
Hi,

In several sonata bundles (at least SonataMedia and SonataClassification), the config need to specify model classes with the `class` parameter.

For example (in config.yml):
```yaml

sonata_media:
    # if you don't use default namespace configuration
    class:
        media:             AppBundle\Entity\Media\Media
        gallery:           AppBundle\Entity\Media\Gallery
        gallery_has_media: AppBundle\Entity\Media\GalleryHasMedia
        category:          AppBundle\Entity\Classification\Category
```

However, if a specified class doesn't exist (f.e. typo or wrong copy/paste), some wtf problems can happen anywhere in the application (because some metadata are wrong and then some relations / tables are not created) without obvious reasons.

I propose to add a check on `DependencyInjection\Configuration` to ensure the specified classes exist. Do you agree with this? If yes I could eventually make a PR for all the bundles using the `class` configuration
