### ISSUE TITLE
No Document Manager

### ISSUE THREAD

**Issue by MHaendel** [sonata-project/SonataMediaBundle#840]
Hey,

I am trying to use the MediaBundle with Mongodb.

This is the Error:
`No document manager defined for class Application\Sonata\MediaBundle\Entity\Media` 

This is my config:

``` yml
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: mammut
    document_managers:
        default:
            auto_mapping: true
            mappings:
                ApplicationSonataMediaBundle: ~
                SonataMediaBundle: ~
sonata_media:
    default_context: default
    db_driver: doctrine_mongodb
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
```
