### ISSUE TITLE
Liip imagine bundle 1.3 integration 

### ISSUE THREAD

**Issue by redayoub** [sonata-project/SonataMediaBundle#842]
Hello,

I'm trying to integrate the liip imagine bundle, I've followed the steps described in the doc but it's not working.

Here's my config:

config.yml

``` yml
sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.image
            formats:
                icon:  { width: 20, height: 20, quality: 70}
                small: { width: 180, height: 180, quality: 70}
                big:   { width: 500, height: 500, quality: 70}
        ads:
            providers:
                - sonata.media.provider.image
            formats:
                thumb: { width: 170, height: 130, quality: 70}
                normal: { width: 500, quality: 70}
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
    providers:
        image:
            service:    sonata.media.provider.image
            resizer:    sonata.media.resizer.simple
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.liip_imagine
            allowed_extensions: ['jpg', 'png', 'jpeg']
            allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']

liip_imagine:
    filter_sets:
        ads_small:
            quality: 75
            controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
            filters:
                thumbnail: { size: [170, 130], mode: inset }
                background: { size: [170, 130], color: '#eee' }
```

routing.yml

``` yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
```

When I try to render a media:

``` twig
{% thumbnail media, 'thumb' %}
```

The first error that I get is:

`Unrecognized option "controller_action" under "liip_imagine.filter_sets.ads_small"`

I fixed that by replacing this:

``` yml
controller_action: 'SonataMediaBundle:Media:liipImagineFilter'
```

by:

``` yml
liip_imagine:
    controller:
        filter_action: 'SonataMediaBundle:Media:liipImagineFilter'
```

then I got this new error:

`Unable to generate a URL for the named route "_imagine_ads_small" as such route does not exist.`

So I looked for a solution and I found this:

``` php
namespace Sonata\MediaBundle\Thumbnail;

public function generatePublicUrl(MediaProviderInterface $provider, MediaInterface $media, $format)
{
    if ($format == 'reference') {
        $path = $provider->getReferenceImage($media);
        return $provider->getCdnPath($path, $media->getCdnIsFlushable());
    } else {
        $path = $this->router->generate('liip_imagine_filter',array(
            'filter' => $format,
            'path'=> $provider->getReferenceImage($media)
        ));
        return $path;
    }
}
```

It has fixed the previous error but the code generated is like: 

``` html
<img src="/uploads/media/app_dev.php/fr/media/cache/resolve/ads_small/ads/0001/01/2896725d5ff255e572e308caf39f4a5c5721fa2c.jpeg">
```

I removed `/uploads/media/` in the begining of the path by repacing:

``` yml
sonata_media:
    cdn:
        server:
            path: /uploads/media
```

by

``` yml
sonata_media:
    cdn:
        server:
            path: ''
```

so the path now is like: 

``` html
<img src="app_dev.php/fr/media/cache/resolve/ads_small/ads/0001/01/2896725d5ff255e572e308caf39f4a5c5721fa2c.jpeg">
```

but the image is not found and when I check the /web/media folder there's no cache folder or files generated.

Note: I tested liipimagine bundle without using sonata and it works, It generates a cache directory with other subdirectories and files.

Any help please?
