### ISSUE TITLE
S3 With Media Bundle

### ISSUE THREAD

**Issue by Siddharth22** [sonata-project/SonataMediaBundle#860]
I did install the dev-master version of Sonata Media (+ all requirements) and it is working fine. Now I am trying to use the amazon s3 fileservice to upload my images. When I upload images then it's show successfully uploaded and also give me s3 url But when I access this then nothing found and also my s3 bucket in empty. I don't know why this is happen....

Here is my configuration :- 
```yaml
sonata_media:
    providers:
        image:
            resizer: sonata.media.resizer.square
    db_driver: doctrine_orm
    default_context: abc # you need to set a context
    contexts:
        abc:  #
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: https://s3.amazonaws.com/xyz

    providers:
            image:
                filesystem: sonata.media.filesystem.s3
                cdn:        sonata.media.cdn.server
                generator:  sonata.media.generator.default
                thumbnail:  sonata.media.thumbnail.format
                allowed_extensions: ['jpg', 'png', 'jpeg', 'gif']
                allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png', 'image/gif']

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

        s3:
            bucket:  xyz
            accessKey:  XXXXXXXXX
            secretKey:  XXXXXXXXXXXXXXXX
            create:  true
```

My Composer.json :- 

        "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "sonata-project/admin-bundle": "^2.3",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "gedmo/doctrine-extensions": "^2.4",
        "sonata-project/user-bundle": "^2.2",
        "friendsofsymfony/user-bundle": "^1.3",
        "sonata-project/easy-extends-bundle": "^2.1",
        "knplabs/knp-menu": "~1.1",
        "knplabs/knp-menu-bundle": "~1.1",
        "sonata-project/media-bundle": "^2.3",
        "sonata-project/intl-bundle": "^2.2",
        "jms/serializer-bundle": "~0.13",
        "stof/doctrine-extensions-bundle": "^1.2",
        "ob/highcharts-bundle": "^1.2",
        "egeloen/ckeditor-bundle": "^3.0",
        "sylius/cart-bundle": "^0.15.0",
        "friendsofsymfony/rest-bundle": "^1.7",
        "aws/aws-sdk-php": "^3.5"
        },

Kind
Siddharth.
