### ISSUE TITLE
 There is no main category related to context: x - how to create a parentless category?

### ISSUE THREAD

**Issue by clytemnestra** [sonata-project/SonataMediaBundle#862]
Greetings, I am trying to attach media to my User(FOSUser) class, more exactly add a profile picture for each user through a Symfony Command. The error that I am getting is

```php
 There is no main category related to context: profile_pics  
```

And the way to solve it is to manually go into the database and create a category with no parent. Is there no way to create such a category through the Sonata Admin?

Here is what I'm using etc.:

my code
```php
            $media = new Media();
            $media->setBinaryContent(getcwd().'/web'.$image);
            $media->setContext('profile_pics');
            $media->setProviderName('sonata.media.provider.image');
            $this->getContainer()->get('sonata.media.manager.media')->save($media);
```

the configuration
```yml
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        profile_pics:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
```

my composer
```composer
   "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "cunningsoft/chat-bundle": "^0.4.0",
        "knplabs/knp-time-bundle": "^1.3",
        "knplabs/knp-paginator-bundle": "^2.4",
        "knplabs/knp-menu-bundle": "~2",
        "twig/extensions": "^1.3",
        "sonata-project/core-bundle": "^2.3",
        "sonata-project/block-bundle": "^2.3.8",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "~2.4@dev",

        "sonata-project/datagrid-bundle": "~2.2@dev",
        "sonata-project/classification-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/intl-bundle": "^2.2",
        "sonata-project/media-bundle": "dev-master",
        "jms/serializer-bundle": "^1.0",
        "kriswallsmith/buzz": "^0.15.0"

    },
```

my user class part
```php
class User extends BaseUser implements AuthorInterface
    /**
     * @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media",cascade={"persist"})
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="CASCADE")
     */
    protected $profilepic;

```
