### ISSUE TITLE
[liip & twig] difference between media and thumbnail 

### ISSUE THREAD

**Issue by juanolon** [sonata-project/SonataMediaBundle#908]
Hello there,
i just finish integrating the liip library into sonata. so, now i have for each "filter" 2 configurations:

``` yml
sonata_media:
...
    contexts:
       profile:
            providers:
                - sonata.media.provider.image
            formats:
                photo: { width: 374, height: 274, quality: 100}  <--- (version A)
                photo: ~                                         <--- (version B)
```

and

``` yml
liip_imagine:
    filter_sets:
        profile_photo:
            filters:
                strip: ~
                interlace:
                    mode: line
                thumbnail: { size: [374, 274], mode: outbound }
        profile_thumbnail:
            filters:
                strip: ~
                interlace:
                    mode: line
                thumbnail: { size: [263, 175], mode: outbound }
```

so now, i wan't to render the image on template, so i do:

``` twig
                thumbnail: {% thumbnail item.media, 'photo' %}
                media: {% media item.media, 'photo' %}
```

the thumbnail tag does work as expected. as it uses the liip-generated thumbnail image.
but the media tag tries to generate another image with `SimpleResizer ->getBox` and expect to have width/height defined (see version A). which doesn't make sense to me, the need of define the sizes to times and to have 2 different image "resizers" (version B also work, if i only call the thumbnail tag)

my question, shouldn't the media tag also try to use the image generated by liip?
or what's the use of the media tag?

greets
