### ISSUE TITLE
No thumbnails generated

### ISSUE THREAD

**Issue by pluff** [sonata-project/SonataMediaBundle#91]
Hello.
After updating to latest deps.lock file I can't get any thumbnails at all.

Here is my config file:

```
sonata_media:
    db_driver:  doctrine_orm # | doctrine_mongodb

contexts:
    products:
        providers:
            - application.media.provider.image
        formats:
            small: { width: 80, height: 80, quality: 70 }
            medium: { width: 150, height: 150, quality: 90 }
            big: { width: 200, height: 200, quality: 90 }
            large: { width: 600, height: 600, quality: 90 }

cdn:
    # define the public base url for the uploaded media
    server:
        path: /uploads/media

filesystem:
    # define where the uploaded file will be stored
    local:
        directory:  %kernel.root_dir%/../web/uploads/media
        create:     true
default_context: products
```

Everything looks like in manuals. Original image is there in uploads folder, but no thumbs. No errors or anything. console tool doesn't help too. My provider is the same as default image provider except it unsets width attribute as described in #82
