### ISSUE TITLE
FileLoaderLoadException after installing SonataMediaBundle

### ISSUE THREAD

**Issue by Zomorrouda** [sonata-project/SonataMediaBundle#912]
An error occurred after installing sonata media bundle (~2.4@dev ) : 

**[Symfony\Component\Config\Exception\FileLoaderLoadException]  
Cannot automatically determine base route name, please define a default `baseRouteName` value for the admin class `Sonata\MediaBundle\Admin\ORM\MediaAdmin` in /project/directory/app/config/. (which is being imported from "/project/directory/app/config/routing.yml").**

My routing.yml

``` yaml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
```

NB: I'm working with Symfony 2.7
