### ISSUE TITLE
New feature: Store path of images to the property of Entity

### ISSUE THREAD

**Issue by igorRovenki** [sonata-project/SonataMediaBundle#914]
Hi gyus!
Sometimes I'm developing REST API and it is very annoying every time call media service to fetch image's path with a right format.
So I think it would be cool to have optional feature that automatically updates property of the entity with a path to image.
I don't know exactly what name of this feature should be... But for example, I will call it `property_path` feature.
So config would be something like this:
```yaml
sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        user:
            providers:
                - sonata.media.provider.image
            formats:
                small:  { width: 100, quality: 95 }
                big:    { width: 300, quality: 95 }
            property_path:
                entity: AppBundle\Entity\User
                properties:
                    smallPhoto: { format: 'small' }
                    bigPhoto: { format: 'big' }
```

Example above assumes that we have such User entity 
```php
class User
{
    /**
     * @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media")
     */
    private $photo;

    /**
     * @var string
     */
    private $smallPhoto;

    /**
     * @var string
     */
    private $bigPhoto;

    public function setSmallPhoto($path);
    public function getSmallPhoto();

    public function setBigPhoto($path);
    public function getBigPhoto();
}
```

when we upload new image this feature automatic setting `smallPhoto` and `bigPhoto` properties with the paths to the images:
```php
$echo $user->getSmallPhoto(); // /uploads/media/user/0001/01/thumb_165_user_small.jpeg
$echo $user->getBigPhoto(); // /uploads/media/user/0001/01/thumb_165_user_big.jpeg
```

This would be very useful feature, specially when you have deal with JavaScript frameworks like AngularJS and your backend need just to return path to image without calling every time media service

I'm want to develop this feature. Give me know what you think? 
p.s. ping @rande
