### ISSUE TITLE
Video providers stopped displaying thumbnails

### ISSUE THREAD

**Issue by liyo** [sonata-project/SonataMediaBundle#915]
Hi there, 
so we have a production website running with an stable version of sonata media bundle from a couple months ago. When updating vendors on the dev site, we found that our video thumbnails stopped working. Image provider thumbnails are working good.

From our debugging, it looks like the thumbnail.html.twig file is still called on the video thumbnail but the options passed are the ones that should be passed to the view_{provider}.html.twig file (iframe or embed code). For example for a Vimeo video thumbnail, inside the "img" tag, we see:

src="fp_version=10&fullscreen=1&title=1&byline=0&portrait=1&hd_off=0&js_onLoad=0&js_swf_id=vimeo_player_5667c51a362cb" id="vimeo_player_5667c51a362cb" frameborder="0" width="500" height="281"

on a Youtube thumbnail we see the following option names passed (can't print values as we get array to string conversion error):
html5, player_url_parameters, player_parameters

We already trying refreshing thumbnails, metadata and updating the video sources from the admin with no success. Any help on this is appreciated, thanks!

**Comment by Thommas** [comment]
Override youtube provider with your own.

Use this:

    /**
     * {@inheritdoc}
     */
    public function getHelperProperties(MediaInterface $media, $format, $options = array())
    {
        $parameters = parent::getHelperProperties($media, $format, $options);
        $parameters['thumbnail_src'] = $this->getReferenceImage($media);
        $parameters['thumbnail_width'] = $options['width'];
        $parameters['thumbnail_height'] = $options['height'];
        return $parameters;
    }

And this template:

    <img src="{{ options.thumbnail_src }}" width="{{ options.thumbnail_width }}" height="{{ options.thumbnail_height }}"/>

**Comment by clytemnestra** [comment]
I believe it's because 

```xml
//sonata-project\media-bundle\Resources\config\provider.xml
        <service id="sonata.media.provider.youtube" class="%sonata.media.provider.youtube.class%">
            <tag name="sonata.media.provider" />
            <argument>sonata.media.provider.youtube</argument>
            <argument />
            <argument />
            <argument />
            <argument type="service" id="sonata.media.thumbnail.format" />
            <argument type="service" id="sonata.media.buzz.browser" />
            <argument type="service" id="sonata.media.metadata.proxy" />
            <argument />
            <call method="setTemplates">
                <argument type="collection">
                    <argument key='helper_thumbnail'>SonataMediaBundle:Provider:thumbnail.html.twig</argument>
                    <argument key='helper_view'>SonataMediaBundle:Provider:view_youtube.html.twig</argument>
                </argument>
            </call>
        </service>

```

The first template should be ```youtube```, not ```thumbnail```

Am I right?

**Comment by clytemnestra** [comment]
Hello, I tried doing like you said, but I'm getting a small error.

Note that I have extended the bundle using easy-extends.

```yml
    sonata.media.provider.youtube2:
        class: Application\Sonata\MediaBundle\Provider\YouTubeProvider
        tags:
            - { name: sonata.media.provider }
        arguments:
        - sonata.media.provider.youtube2
        - @sonata.media.filesystem.local
        - @sonata.media.cdn.server
        - @sonata.media.generator.default
        - @sonata.media.thumbnail.format
        - @sonata.media.buzz.browser
        - @sonata.media.metadata.proxy
        - ~
        - @sonata.media.resizer.simple
        calls:
            - [ setTemplates, [{helper_view:SonataMediaBundle:Provider:view_youtube.html.twig,helper_thumbnail:SonataMediaBundle:Provider:ytthumbnail.html.twig}]]
```

```php
namespace Application\Sonata\MediaBundle\Provider;

use Buzz\Browser;
use Gaufrette\Filesystem;
use Sonata\MediaBundle\CDN\CDNInterface;
use Sonata\MediaBundle\Generator\GeneratorInterface;
use Sonata\MediaBundle\Metadata\MetadataBuilderInterface;
use Sonata\MediaBundle\Model\MediaInterface;
use Sonata\MediaBundle\Resizer\ResizerInterface;
use Sonata\MediaBundle\Thumbnail\ThumbnailInterface;
use Sonata\MediaBundle\Provider\YouTubeProvider as BaseYouTubeProvider;

class YouTubeProvider extends BaseYouTubeProvider
{
    /**
     * @var bool
     */
    protected $html5;

    /**
     * @param string $name
     * @param Filesystem $filesystem
     * @param CDNInterface $cdn
     * @param GeneratorInterface $pathGenerator
     * @param ThumbnailInterface $thumbnail
     * @param Browser $browser
     * @param MetadataBuilderInterface $metadata
     * @param bool $html5
     */
    public function __construct($name, Filesystem $filesystem, CDNInterface $cdn, GeneratorInterface $pathGenerator, ThumbnailInterface $thumbnail, Browser $browser, MetadataBuilderInterface $metadata = null, $html5 = false, ResizerInterface $resizerInterface)
    {
        parent::__construct($name, $filesystem, $cdn, $pathGenerator, $thumbnail, $browser, $metadata);
        $this->html5 = $html5;
        $this->setResizer($resizerInterface);
    }

    /**
     * {@inheritdoc}
     */
    public function getHelperProperties(MediaInterface $media, $format, $options = array())
    {
        $parameters = parent::getHelperProperties($media, $format, $options);
        $parameters['thumbnail_src'] = $this->getReferenceImage($media);
        $parameters['thumbnail_width'] = $options['width'];
        $parameters['thumbnail_height'] = $options['height'];
        return $parameters;
    }


}

```

But I get

```An exception has been thrown during the rendering of a template ("Notice: Undefined index: height") in "SonataMediaBundle:Form:media_widgets.html.twig".```
