### ISSUE TITLE
Invalid mapping file 'Application.Sonata.MediaBundle.PHPCR.Media.phpcr.xml' for class 'Application\Sonata\MediaBundle\PHPCR\Media'

### ISSUE THREAD

**Issue by ArchTaqi** [sonata-project/SonataMediaBundle#919]
I have install Sonata Media Bundle along side Sonata User and Admin Bundle. I am deploying my application to heroku and During Deployment I am getting this error.

```
[RuntimeException]                                                                                                                       
remote:          An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                
remote:                                                                                                                                                   
remote:            [Doctrine\ODM\PHPCR\Mapping\MappingException]                                                                                          
remote:            Invalid mapping file 'Application.Sonata.MediaBundle.PHPCR.Media.phpcr.xml' for class 'Application\Sonata\MediaBundle\PHPCR\Media'.    
remote:                                                                                                                                                   
remote:                                                                                                                                                   
remote:            [Doctrine\Common\Persistence\Mapping\MappingException]                                                                                 
remote:            Invalid mapping file 'Application.Sonata.MediaBundle.PHPCR.Media.phpcr.xml' for class 'Application\Sonata\MediaBundle\PHPCR\Media'.   
```

Below are my config.yml settings;

``` yaml
doctrine:
    dbal:
        driver:   "pdo_pgsql"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

#    orm:
#        entity_managers:
#            default:
#                mappings:
#                    SonataMediaBundle: ~
##        auto_generate_proxy_classes: "%kernel.debug%"
##        naming_strategy: doctrine.orm.naming_strategy.underscore
##        auto_mapping: true
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    ApplicationSonataMediaBundle: ~

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            # connection: default
        workspace: default
        username: admin
        password: admin
    odm:
        auto_mapping: true
        mappings:
            ApplicationSonataMediaBundle:
                prefix: Application\Sonata\MediaBundle\PHPCR
```
