### ISSUE TITLE
Problem to create audio provider

### ISSUE THREAD

**Issue by estebannovo** [sonata-project/SonataMediaBundle#943]
hello, one question, I create a new provier but in the usage my provider is unregonized, how to declare a new provider and where?

My provider y called sonata.media.provider.audio and where i set the available extension:

``` yaml
providers:
        image:
            resizer: sonata.media.resizer.square
        file:
            service:    sonata.media.provider.file
            resizer:    false
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml', 'mp3']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain', 'audio/mpeg']
        audio:
            allowed_extensions: ['mp3']
            allowed_mime_types: ['audio/mpeg']
```

The provider audio fail:

```
Symfony error:
InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "audio" under "sonata_media.providers"
```

Thanks!
