### ISSUE TITLE
absolute path for media

### ISSUE THREAD

**Issue by Sergic** [sonata-project/SonataMediaBundle#95]
how to get absolute path with hostname
for {% path media, 'small' %} ?

**Comment by webdevilopers** [comment]
I work with `wkhtmltopdf` and `KnpSnappyBundle`. The PDF generation requires absolute paths which works fine for assets e.g.:
```twig
<img src="{% if app.environment == 'dev' %}{{
            asset('rewoteclogo2014.png') }}{% else %}{{
            asset('rewoteclogo2014.png', absolute=true) }}
        {% endif %}">
```

But I can't get it working with the `cdn` settings since
```twig
{% path instruction.media, 'reference' %}
```

always returns a relevative path `uploads/media/...`.

```yaml
sonata_media:
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true
```

What I actually need is the `local` `directory` path from the `filesystem` config parameter. Is there a helper / extension @rande ?
